// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "C_drain_IO_L2_out.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic C_drain_IO_L2_out::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic C_drain_IO_L2_out::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> C_drain_IO_L2_out::ap_ST_fsm_state1 = "1";
const sc_lv<3> C_drain_IO_L2_out::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> C_drain_IO_L2_out::ap_ST_fsm_state4 = "100";
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool C_drain_IO_L2_out::ap_const_boolean_1 = true;
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_1 = "1";
const bool C_drain_IO_L2_out::ap_const_boolean_0 = false;
const sc_lv<1> C_drain_IO_L2_out::ap_const_lv1_0 = "0";
const sc_lv<1> C_drain_IO_L2_out::ap_const_lv1_1 = "1";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_0 = "000000";
const sc_lv<5> C_drain_IO_L2_out::ap_const_lv5_0 = "00000";
const sc_lv<2> C_drain_IO_L2_out::ap_const_lv2_0 = "00";
const sc_lv<4> C_drain_IO_L2_out::ap_const_lv4_0 = "0000";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_20 = "100000";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_1 = "1";
const sc_lv<6> C_drain_IO_L2_out::ap_const_lv6_10 = "10000";
const sc_lv<2> C_drain_IO_L2_out::ap_const_lv2_1 = "1";
const sc_lv<4> C_drain_IO_L2_out::ap_const_lv4_4 = "100";
const sc_lv<5> C_drain_IO_L2_out::ap_const_lv5_8 = "1000";
const sc_lv<4> C_drain_IO_L2_out::ap_const_lv4_1 = "1";
const sc_lv<5> C_drain_IO_L2_out::ap_const_lv5_1 = "1";
const sc_lv<32> C_drain_IO_L2_out::ap_const_lv32_2 = "10";

C_drain_IO_L2_out::C_drain_IO_L2_out(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln738_fu_190_p2);
    sensitive << ( indvar_flatten63_reg_117 );

    SC_METHOD(thread_add_ln739_fu_350_p2);
    sensitive << ( indvar_flatten33_reg_128 );

    SC_METHOD(thread_add_ln742_1_fu_336_p2);
    sensitive << ( indvar_flatten11_reg_139 );

    SC_METHOD(thread_add_ln744_fu_310_p2);
    sensitive << ( indvar_flatten_reg_161 );

    SC_METHOD(thread_and_ln739_1_fu_226_p2);
    sensitive << ( xor_ln739_fu_202_p2 );
    sensitive << ( icmp_ln744_fu_220_p2 );

    SC_METHOD(thread_and_ln739_2_fu_238_p2);
    sensitive << ( xor_ln739_fu_202_p2 );
    sensitive << ( icmp_ln742_fu_232_p2 );

    SC_METHOD(thread_and_ln739_fu_214_p2);
    sensitive << ( icmp_ln750_fu_208_p2 );
    sensitive << ( xor_ln739_fu_202_p2 );

    SC_METHOD(thread_and_ln742_1_fu_276_p2);
    sensitive << ( or_ln742_1_fu_264_p2 );
    sensitive << ( and_ln739_1_fu_226_p2 );

    SC_METHOD(thread_and_ln742_fu_270_p2);
    sensitive << ( and_ln739_fu_214_p2 );
    sensitive << ( or_ln742_1_fu_264_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( ap_predicate_op47_read_state3 );
    sensitive << ( ap_predicate_op49_read_state3 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( ap_predicate_op47_read_state3 );
    sensitive << ( ap_predicate_op49_read_state3 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( ap_predicate_op47_read_state3 );
    sensitive << ( ap_predicate_op49_read_state3 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( ap_predicate_op47_read_state3 );
    sensitive << ( ap_predicate_op49_read_state3 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln738_fu_184_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_phi_mux_tmp_V_phi_fu_175_p4);
    sensitive << ( fifo_C_drain_in_V_V_dout );
    sensitive << ( fifo_C_drain_local_in_V_V_dout );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( select_ln750_reg_373 );
    sensitive << ( ap_phi_reg_pp0_iter1_tmp_V_reg_172 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter1_tmp_V_reg_172);

    SC_METHOD(thread_ap_predicate_op47_read_state3);
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( select_ln750_reg_373 );

    SC_METHOD(thread_ap_predicate_op49_read_state3);
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( select_ln750_reg_373 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_c3_fu_282_p2);
    sensitive << ( select_ln742_fu_250_p3 );

    SC_METHOD(thread_fifo_C_drain_in_V_V_blk_n);
    sensitive << ( fifo_C_drain_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( select_ln750_reg_373 );

    SC_METHOD(thread_fifo_C_drain_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op47_read_state3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_V_blk_n);
    sensitive << ( fifo_C_drain_local_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( select_ln750_reg_373 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op49_read_state3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_blk_n);
    sensitive << ( fifo_C_drain_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln738_reg_364 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_din);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( ap_phi_mux_tmp_V_phi_fu_175_p4 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln738_reg_364 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln738_fu_184_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten63_reg_117 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln739_fu_196_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten33_reg_128 );
    sensitive << ( icmp_ln738_fu_184_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln742_fu_232_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten11_reg_139 );
    sensitive << ( icmp_ln738_fu_184_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln744_fu_220_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_161 );
    sensitive << ( icmp_ln738_fu_184_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln750_1_fu_288_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln738_fu_184_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( select_ln742_fu_250_p3 );

    SC_METHOD(thread_icmp_ln750_fu_208_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( c3_0_reg_150 );
    sensitive << ( icmp_ln738_fu_184_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_or_ln742_1_fu_264_p2);
    sensitive << ( icmp_ln739_fu_196_p2 );
    sensitive << ( xor_ln742_fu_258_p2 );

    SC_METHOD(thread_or_ln742_fu_244_p2);
    sensitive << ( icmp_ln739_fu_196_p2 );
    sensitive << ( and_ln739_2_fu_238_p2 );

    SC_METHOD(thread_or_ln744_1_fu_322_p2);
    sensitive << ( icmp_ln739_fu_196_p2 );
    sensitive << ( or_ln744_fu_316_p2 );

    SC_METHOD(thread_or_ln744_fu_316_p2);
    sensitive << ( and_ln739_2_fu_238_p2 );
    sensitive << ( and_ln742_1_fu_276_p2 );

    SC_METHOD(thread_select_ln739_fu_356_p3);
    sensitive << ( icmp_ln739_fu_196_p2 );
    sensitive << ( add_ln739_fu_350_p2 );

    SC_METHOD(thread_select_ln742_1_fu_302_p3);
    sensitive << ( select_ln742_fu_250_p3 );
    sensitive << ( and_ln742_1_fu_276_p2 );
    sensitive << ( c3_fu_282_p2 );

    SC_METHOD(thread_select_ln742_2_fu_342_p3);
    sensitive << ( or_ln742_fu_244_p2 );
    sensitive << ( add_ln742_1_fu_336_p2 );

    SC_METHOD(thread_select_ln742_fu_250_p3);
    sensitive << ( c3_0_reg_150 );
    sensitive << ( or_ln742_fu_244_p2 );

    SC_METHOD(thread_select_ln744_fu_328_p3);
    sensitive << ( or_ln744_1_fu_322_p2 );
    sensitive << ( add_ln744_fu_310_p2 );

    SC_METHOD(thread_select_ln750_fu_294_p3);
    sensitive << ( and_ln742_1_fu_276_p2 );
    sensitive << ( icmp_ln750_1_fu_288_p2 );
    sensitive << ( and_ln742_fu_270_p2 );

    SC_METHOD(thread_xor_ln739_fu_202_p2);
    sensitive << ( icmp_ln739_fu_196_p2 );

    SC_METHOD(thread_xor_ln742_fu_258_p2);
    sensitive << ( icmp_ln742_fu_232_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln738_fu_184_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "C_drain_IO_L2_out_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_dout, "(port)fifo_C_drain_in_V_V_dout");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_empty_n, "(port)fifo_C_drain_in_V_V_empty_n");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_read, "(port)fifo_C_drain_in_V_V_read");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_din, "(port)fifo_C_drain_out_V_V_din");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_full_n, "(port)fifo_C_drain_out_V_V_full_n");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_write, "(port)fifo_C_drain_out_V_V_write");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_dout, "(port)fifo_C_drain_local_in_V_V_dout");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_empty_n, "(port)fifo_C_drain_local_in_V_V_empty_n");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_read, "(port)fifo_C_drain_local_in_V_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fifo_C_drain_in_V_V_blk_n, "fifo_C_drain_in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln738_reg_364, "icmp_ln738_reg_364");
    sc_trace(mVcdFile, select_ln750_reg_373, "select_ln750_reg_373");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_blk_n, "fifo_C_drain_out_V_V_blk_n");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_V_blk_n, "fifo_C_drain_local_in_V_V_blk_n");
    sc_trace(mVcdFile, indvar_flatten63_reg_117, "indvar_flatten63_reg_117");
    sc_trace(mVcdFile, indvar_flatten33_reg_128, "indvar_flatten33_reg_128");
    sc_trace(mVcdFile, indvar_flatten11_reg_139, "indvar_flatten11_reg_139");
    sc_trace(mVcdFile, c3_0_reg_150, "c3_0_reg_150");
    sc_trace(mVcdFile, indvar_flatten_reg_161, "indvar_flatten_reg_161");
    sc_trace(mVcdFile, icmp_ln738_fu_184_p2, "icmp_ln738_fu_184_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op47_read_state3, "ap_predicate_op47_read_state3");
    sc_trace(mVcdFile, ap_predicate_op49_read_state3, "ap_predicate_op49_read_state3");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln738_fu_190_p2, "add_ln738_fu_190_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln750_fu_294_p3, "select_ln750_fu_294_p3");
    sc_trace(mVcdFile, select_ln742_1_fu_302_p3, "select_ln742_1_fu_302_p3");
    sc_trace(mVcdFile, select_ln744_fu_328_p3, "select_ln744_fu_328_p3");
    sc_trace(mVcdFile, select_ln742_2_fu_342_p3, "select_ln742_2_fu_342_p3");
    sc_trace(mVcdFile, select_ln739_fu_356_p3, "select_ln739_fu_356_p3");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_phi_mux_tmp_V_phi_fu_175_p4, "ap_phi_mux_tmp_V_phi_fu_175_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_tmp_V_reg_172, "ap_phi_reg_pp0_iter1_tmp_V_reg_172");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, icmp_ln739_fu_196_p2, "icmp_ln739_fu_196_p2");
    sc_trace(mVcdFile, icmp_ln750_fu_208_p2, "icmp_ln750_fu_208_p2");
    sc_trace(mVcdFile, xor_ln739_fu_202_p2, "xor_ln739_fu_202_p2");
    sc_trace(mVcdFile, icmp_ln744_fu_220_p2, "icmp_ln744_fu_220_p2");
    sc_trace(mVcdFile, icmp_ln742_fu_232_p2, "icmp_ln742_fu_232_p2");
    sc_trace(mVcdFile, and_ln739_2_fu_238_p2, "and_ln739_2_fu_238_p2");
    sc_trace(mVcdFile, or_ln742_fu_244_p2, "or_ln742_fu_244_p2");
    sc_trace(mVcdFile, xor_ln742_fu_258_p2, "xor_ln742_fu_258_p2");
    sc_trace(mVcdFile, and_ln739_fu_214_p2, "and_ln739_fu_214_p2");
    sc_trace(mVcdFile, or_ln742_1_fu_264_p2, "or_ln742_1_fu_264_p2");
    sc_trace(mVcdFile, and_ln739_1_fu_226_p2, "and_ln739_1_fu_226_p2");
    sc_trace(mVcdFile, select_ln742_fu_250_p3, "select_ln742_fu_250_p3");
    sc_trace(mVcdFile, and_ln742_1_fu_276_p2, "and_ln742_1_fu_276_p2");
    sc_trace(mVcdFile, icmp_ln750_1_fu_288_p2, "icmp_ln750_1_fu_288_p2");
    sc_trace(mVcdFile, and_ln742_fu_270_p2, "and_ln742_fu_270_p2");
    sc_trace(mVcdFile, c3_fu_282_p2, "c3_fu_282_p2");
    sc_trace(mVcdFile, or_ln744_fu_316_p2, "or_ln744_fu_316_p2");
    sc_trace(mVcdFile, or_ln744_1_fu_322_p2, "or_ln744_1_fu_322_p2");
    sc_trace(mVcdFile, add_ln744_fu_310_p2, "add_ln744_fu_310_p2");
    sc_trace(mVcdFile, add_ln742_1_fu_336_p2, "add_ln742_1_fu_336_p2");
    sc_trace(mVcdFile, add_ln739_fu_350_p2, "add_ln739_fu_350_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

C_drain_IO_L2_out::~C_drain_IO_L2_out() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void C_drain_IO_L2_out::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln738_fu_184_p2.read()))) {
        c3_0_reg_150 = select_ln742_1_fu_302_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        c3_0_reg_150 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln738_fu_184_p2.read()))) {
        indvar_flatten11_reg_139 = select_ln742_2_fu_342_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten11_reg_139 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln738_fu_184_p2.read()))) {
        indvar_flatten33_reg_128 = select_ln739_fu_356_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten33_reg_128 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln738_fu_184_p2.read()))) {
        indvar_flatten63_reg_117 = add_ln738_fu_190_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten63_reg_117 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln738_fu_184_p2.read()))) {
        indvar_flatten_reg_161 = select_ln744_fu_328_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten_reg_161 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln738_reg_364 = icmp_ln738_fu_184_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln738_fu_184_p2.read()))) {
        select_ln750_reg_373 = select_ln750_fu_294_p3.read();
    }
}

void C_drain_IO_L2_out::thread_add_ln738_fu_190_p2() {
    add_ln738_fu_190_p2 = (!indvar_flatten63_reg_117.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten63_reg_117.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void C_drain_IO_L2_out::thread_add_ln739_fu_350_p2() {
    add_ln739_fu_350_p2 = (!indvar_flatten33_reg_128.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten33_reg_128.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void C_drain_IO_L2_out::thread_add_ln742_1_fu_336_p2() {
    add_ln742_1_fu_336_p2 = (!indvar_flatten11_reg_139.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten11_reg_139.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void C_drain_IO_L2_out::thread_add_ln744_fu_310_p2() {
    add_ln744_fu_310_p2 = (!indvar_flatten_reg_161.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten_reg_161.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void C_drain_IO_L2_out::thread_and_ln739_1_fu_226_p2() {
    and_ln739_1_fu_226_p2 = (icmp_ln744_fu_220_p2.read() & xor_ln739_fu_202_p2.read());
}

void C_drain_IO_L2_out::thread_and_ln739_2_fu_238_p2() {
    and_ln739_2_fu_238_p2 = (icmp_ln742_fu_232_p2.read() & xor_ln739_fu_202_p2.read());
}

void C_drain_IO_L2_out::thread_and_ln739_fu_214_p2() {
    and_ln739_fu_214_p2 = (icmp_ln750_fu_208_p2.read() & xor_ln739_fu_202_p2.read());
}

void C_drain_IO_L2_out::thread_and_ln742_1_fu_276_p2() {
    and_ln742_1_fu_276_p2 = (and_ln739_1_fu_226_p2.read() & or_ln742_1_fu_264_p2.read());
}

void C_drain_IO_L2_out::thread_and_ln742_fu_270_p2() {
    and_ln742_fu_270_p2 = (and_ln739_fu_214_p2.read() & or_ln742_1_fu_264_p2.read());
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void C_drain_IO_L2_out::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op47_read_state3.read())) || 
  (esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op49_read_state3.read())) || 
  (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op47_read_state3.read())) || 
  (esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op49_read_state3.read())) || 
  (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op47_read_state3.read())) || 
  (esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op49_read_state3.read())) || 
  (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read()))));
}

void C_drain_IO_L2_out::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void C_drain_IO_L2_out::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L2_out::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_in_V_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op47_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op49_read_state3.read())) || (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_V_full_n.read())));
}

void C_drain_IO_L2_out::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln738_fu_184_p2.read())) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void C_drain_IO_L2_out::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void C_drain_IO_L2_out::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_ap_phi_mux_tmp_V_phi_fu_175_p4() {
    if (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, select_ln750_reg_373.read())) {
            ap_phi_mux_tmp_V_phi_fu_175_p4 = fifo_C_drain_in_V_V_dout.read();
        } else if (esl_seteq<1,1,1>(select_ln750_reg_373.read(), ap_const_lv1_1)) {
            ap_phi_mux_tmp_V_phi_fu_175_p4 = fifo_C_drain_local_in_V_V_dout.read();
        } else {
            ap_phi_mux_tmp_V_phi_fu_175_p4 = ap_phi_reg_pp0_iter1_tmp_V_reg_172.read();
        }
    } else {
        ap_phi_mux_tmp_V_phi_fu_175_p4 = ap_phi_reg_pp0_iter1_tmp_V_reg_172.read();
    }
}

void C_drain_IO_L2_out::thread_ap_phi_reg_pp0_iter1_tmp_V_reg_172() {
    ap_phi_reg_pp0_iter1_tmp_V_reg_172 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void C_drain_IO_L2_out::thread_ap_predicate_op47_read_state3() {
    ap_predicate_op47_read_state3 = (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, select_ln750_reg_373.read()));
}

void C_drain_IO_L2_out::thread_ap_predicate_op49_read_state3() {
    ap_predicate_op49_read_state3 = (esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(select_ln750_reg_373.read(), ap_const_lv1_1));
}

void C_drain_IO_L2_out::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_c3_fu_282_p2() {
    c3_fu_282_p2 = (!select_ln742_fu_250_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln742_fu_250_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void C_drain_IO_L2_out::thread_fifo_C_drain_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, select_ln750_reg_373.read()))) {
        fifo_C_drain_in_V_V_blk_n = fifo_C_drain_in_V_V_empty_n.read();
    } else {
        fifo_C_drain_in_V_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op47_read_state3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_in_V_V_read = ap_const_logic_1;
    } else {
        fifo_C_drain_in_V_V_read = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_local_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(select_ln750_reg_373.read(), ap_const_lv1_1))) {
        fifo_C_drain_local_in_V_V_blk_n = fifo_C_drain_local_in_V_V_empty_n.read();
    } else {
        fifo_C_drain_local_in_V_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_local_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op49_read_state3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_local_in_V_V_read = ap_const_logic_1;
    } else {
        fifo_C_drain_local_in_V_V_read = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0))) {
        fifo_C_drain_out_V_V_blk_n = fifo_C_drain_out_V_V_full_n.read();
    } else {
        fifo_C_drain_out_V_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L2_out::thread_fifo_C_drain_out_V_V_din() {
    fifo_C_drain_out_V_V_din = ap_phi_mux_tmp_V_phi_fu_175_p4.read();
}

void C_drain_IO_L2_out::thread_fifo_C_drain_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln738_reg_364.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_out_V_V_write = ap_const_logic_1;
    } else {
        fifo_C_drain_out_V_V_write = ap_const_logic_0;
    }
}

void C_drain_IO_L2_out::thread_icmp_ln738_fu_184_p2() {
    icmp_ln738_fu_184_p2 = (!indvar_flatten63_reg_117.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten63_reg_117.read() == ap_const_lv6_20);
}

void C_drain_IO_L2_out::thread_icmp_ln739_fu_196_p2() {
    icmp_ln739_fu_196_p2 = (!indvar_flatten33_reg_128.read().is_01() || !ap_const_lv6_10.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten33_reg_128.read() == ap_const_lv6_10);
}

void C_drain_IO_L2_out::thread_icmp_ln742_fu_232_p2() {
    icmp_ln742_fu_232_p2 = (!indvar_flatten11_reg_139.read().is_01() || !ap_const_lv5_8.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten11_reg_139.read() == ap_const_lv5_8);
}

void C_drain_IO_L2_out::thread_icmp_ln744_fu_220_p2() {
    icmp_ln744_fu_220_p2 = (!indvar_flatten_reg_161.read().is_01() || !ap_const_lv4_4.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_161.read() == ap_const_lv4_4);
}

void C_drain_IO_L2_out::thread_icmp_ln750_1_fu_288_p2() {
    icmp_ln750_1_fu_288_p2 = (!select_ln742_fu_250_p3.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(select_ln742_fu_250_p3.read() == ap_const_lv2_0);
}

void C_drain_IO_L2_out::thread_icmp_ln750_fu_208_p2() {
    icmp_ln750_fu_208_p2 = (!c3_0_reg_150.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(c3_0_reg_150.read() == ap_const_lv2_1);
}

void C_drain_IO_L2_out::thread_or_ln742_1_fu_264_p2() {
    or_ln742_1_fu_264_p2 = (icmp_ln739_fu_196_p2.read() | xor_ln742_fu_258_p2.read());
}

void C_drain_IO_L2_out::thread_or_ln742_fu_244_p2() {
    or_ln742_fu_244_p2 = (and_ln739_2_fu_238_p2.read() | icmp_ln739_fu_196_p2.read());
}

void C_drain_IO_L2_out::thread_or_ln744_1_fu_322_p2() {
    or_ln744_1_fu_322_p2 = (or_ln744_fu_316_p2.read() | icmp_ln739_fu_196_p2.read());
}

void C_drain_IO_L2_out::thread_or_ln744_fu_316_p2() {
    or_ln744_fu_316_p2 = (and_ln742_1_fu_276_p2.read() | and_ln739_2_fu_238_p2.read());
}

void C_drain_IO_L2_out::thread_select_ln739_fu_356_p3() {
    select_ln739_fu_356_p3 = (!icmp_ln739_fu_196_p2.read()[0].is_01())? sc_lv<6>(): ((icmp_ln739_fu_196_p2.read()[0].to_bool())? ap_const_lv6_1: add_ln739_fu_350_p2.read());
}

void C_drain_IO_L2_out::thread_select_ln742_1_fu_302_p3() {
    select_ln742_1_fu_302_p3 = (!and_ln742_1_fu_276_p2.read()[0].is_01())? sc_lv<2>(): ((and_ln742_1_fu_276_p2.read()[0].to_bool())? c3_fu_282_p2.read(): select_ln742_fu_250_p3.read());
}

void C_drain_IO_L2_out::thread_select_ln742_2_fu_342_p3() {
    select_ln742_2_fu_342_p3 = (!or_ln742_fu_244_p2.read()[0].is_01())? sc_lv<5>(): ((or_ln742_fu_244_p2.read()[0].to_bool())? ap_const_lv5_1: add_ln742_1_fu_336_p2.read());
}

void C_drain_IO_L2_out::thread_select_ln742_fu_250_p3() {
    select_ln742_fu_250_p3 = (!or_ln742_fu_244_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln742_fu_244_p2.read()[0].to_bool())? ap_const_lv2_0: c3_0_reg_150.read());
}

void C_drain_IO_L2_out::thread_select_ln744_fu_328_p3() {
    select_ln744_fu_328_p3 = (!or_ln744_1_fu_322_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln744_1_fu_322_p2.read()[0].to_bool())? ap_const_lv4_1: add_ln744_fu_310_p2.read());
}

void C_drain_IO_L2_out::thread_select_ln750_fu_294_p3() {
    select_ln750_fu_294_p3 = (!and_ln742_1_fu_276_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln742_1_fu_276_p2.read()[0].to_bool())? icmp_ln750_1_fu_288_p2.read(): and_ln742_fu_270_p2.read());
}

void C_drain_IO_L2_out::thread_xor_ln739_fu_202_p2() {
    xor_ln739_fu_202_p2 = (icmp_ln739_fu_196_p2.read() ^ ap_const_lv1_1);
}

void C_drain_IO_L2_out::thread_xor_ln742_fu_258_p2() {
    xor_ln742_fu_258_p2 = (icmp_ln742_fu_232_p2.read() ^ ap_const_lv1_1);
}

void C_drain_IO_L2_out::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln738_fu_184_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln738_fu_184_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

