// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "C_drain_IO_L1_out_in.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic C_drain_IO_L1_out_in::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic C_drain_IO_L1_out_in::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> C_drain_IO_L1_out_in::ap_ST_fsm_state1 = "1";
const sc_lv<3> C_drain_IO_L1_out_in::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> C_drain_IO_L1_out_in::ap_ST_fsm_state4 = "100";
const bool C_drain_IO_L1_out_in::ap_const_boolean_1 = true;
const sc_lv<32> C_drain_IO_L1_out_in::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> C_drain_IO_L1_out_in::ap_const_lv32_1 = "1";
const bool C_drain_IO_L1_out_in::ap_const_boolean_0 = false;
const sc_lv<1> C_drain_IO_L1_out_in::ap_const_lv1_0 = "0";
const sc_lv<1> C_drain_IO_L1_out_in::ap_const_lv1_1 = "1";
const sc_lv<3> C_drain_IO_L1_out_in::ap_const_lv3_0 = "000";
const sc_lv<2> C_drain_IO_L1_out_in::ap_const_lv2_0 = "00";
const sc_lv<3> C_drain_IO_L1_out_in::ap_const_lv3_4 = "100";
const sc_lv<3> C_drain_IO_L1_out_in::ap_const_lv3_1 = "1";
const sc_lv<2> C_drain_IO_L1_out_in::ap_const_lv2_2 = "10";
const sc_lv<2> C_drain_IO_L1_out_in::ap_const_lv2_1 = "1";
const sc_lv<32> C_drain_IO_L1_out_in::ap_const_lv32_20 = "100000";
const sc_lv<32> C_drain_IO_L1_out_in::ap_const_lv32_3F = "111111";
const sc_lv<32> C_drain_IO_L1_out_in::ap_const_lv32_2 = "10";

C_drain_IO_L1_out_in::C_drain_IO_L1_out_in(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln574_fu_117_p2);
    sensitive << ( indvar_flatten_reg_89 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( fifo_C_drain_local_in_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln574_reg_167 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( fifo_C_drain_local_in_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln574_reg_167 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( fifo_C_drain_local_in_V_empty_n );
    sensitive << ( icmp_ln574_reg_167 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln574_fu_111_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buf_data_split_1_V_fu_148_p4);
    sensitive << ( local_C_0_V_q0 );

    SC_METHOD(thread_c7_fu_142_p2);
    sensitive << ( select_ln576_fu_129_p3 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_blk_n);
    sensitive << ( fifo_C_drain_local_in_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln574_reg_167 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln574_reg_167 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln574_fu_111_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_89 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln576_fu_123_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( c7_0_reg_100 );
    sensitive << ( icmp_ln574_fu_111_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_local_C_0_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln584_fu_137_p1 );

    SC_METHOD(thread_local_C_0_V_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( local_C_0_V_addr_reg_176 );

    SC_METHOD(thread_local_C_0_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_local_C_0_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_local_C_0_V_d1);
    sensitive << ( fifo_C_drain_local_in_V_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( buf_data_split_1_V_fu_148_p4 );

    SC_METHOD(thread_local_C_0_V_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln574_reg_167 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_select_ln576_fu_129_p3);
    sensitive << ( c7_0_reg_100 );
    sensitive << ( icmp_ln576_fu_123_p2 );

    SC_METHOD(thread_zext_ln584_fu_137_p1);
    sensitive << ( select_ln576_fu_129_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln574_fu_111_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "C_drain_IO_L1_out_in_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, local_C_0_V_address0, "(port)local_C_0_V_address0");
    sc_trace(mVcdFile, local_C_0_V_ce0, "(port)local_C_0_V_ce0");
    sc_trace(mVcdFile, local_C_0_V_q0, "(port)local_C_0_V_q0");
    sc_trace(mVcdFile, local_C_0_V_address1, "(port)local_C_0_V_address1");
    sc_trace(mVcdFile, local_C_0_V_ce1, "(port)local_C_0_V_ce1");
    sc_trace(mVcdFile, local_C_0_V_we1, "(port)local_C_0_V_we1");
    sc_trace(mVcdFile, local_C_0_V_d1, "(port)local_C_0_V_d1");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_dout, "(port)fifo_C_drain_local_in_V_dout");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_empty_n, "(port)fifo_C_drain_local_in_V_empty_n");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_read, "(port)fifo_C_drain_local_in_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_blk_n, "fifo_C_drain_local_in_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln574_reg_167, "icmp_ln574_reg_167");
    sc_trace(mVcdFile, indvar_flatten_reg_89, "indvar_flatten_reg_89");
    sc_trace(mVcdFile, c7_0_reg_100, "c7_0_reg_100");
    sc_trace(mVcdFile, icmp_ln574_fu_111_p2, "icmp_ln574_fu_111_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln574_fu_117_p2, "add_ln574_fu_117_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, local_C_0_V_addr_reg_176, "local_C_0_V_addr_reg_176");
    sc_trace(mVcdFile, c7_fu_142_p2, "c7_fu_142_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, zext_ln584_fu_137_p1, "zext_ln584_fu_137_p1");
    sc_trace(mVcdFile, icmp_ln576_fu_123_p2, "icmp_ln576_fu_123_p2");
    sc_trace(mVcdFile, select_ln576_fu_129_p3, "select_ln576_fu_129_p3");
    sc_trace(mVcdFile, buf_data_split_1_V_fu_148_p4, "buf_data_split_1_V_fu_148_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

C_drain_IO_L1_out_in::~C_drain_IO_L1_out_in() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void C_drain_IO_L1_out_in::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln574_fu_111_p2.read()))) {
        c7_0_reg_100 = c7_fu_142_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c7_0_reg_100 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln574_fu_111_p2.read()))) {
        indvar_flatten_reg_89 = add_ln574_fu_117_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_89 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln574_reg_167 = icmp_ln574_fu_111_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln574_fu_111_p2.read()))) {
        local_C_0_V_addr_reg_176 =  (sc_lv<1>) (zext_ln584_fu_137_p1.read());
    }
}

void C_drain_IO_L1_out_in::thread_add_ln574_fu_117_p2() {
    add_ln574_fu_117_p2 = (!indvar_flatten_reg_89.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(indvar_flatten_reg_89.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void C_drain_IO_L1_out_in::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void C_drain_IO_L1_out_in::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void C_drain_IO_L1_out_in::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void C_drain_IO_L1_out_in::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L1_out_in::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln574_reg_167.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_empty_n.read()));
}

void C_drain_IO_L1_out_in::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln574_reg_167.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_empty_n.read()));
}

void C_drain_IO_L1_out_in::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void C_drain_IO_L1_out_in::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln574_reg_167.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_local_in_V_empty_n.read()));
}

void C_drain_IO_L1_out_in::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln574_fu_111_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void C_drain_IO_L1_out_in::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_buf_data_split_1_V_fu_148_p4() {
    buf_data_split_1_V_fu_148_p4 = local_C_0_V_q0.read().range(63, 32);
}

void C_drain_IO_L1_out_in::thread_c7_fu_142_p2() {
    c7_fu_142_p2 = (!select_ln576_fu_129_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln576_fu_129_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void C_drain_IO_L1_out_in::thread_fifo_C_drain_local_in_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln574_reg_167.read(), ap_const_lv1_0))) {
        fifo_C_drain_local_in_V_blk_n = fifo_C_drain_local_in_V_empty_n.read();
    } else {
        fifo_C_drain_local_in_V_blk_n = ap_const_logic_1;
    }
}

void C_drain_IO_L1_out_in::thread_fifo_C_drain_local_in_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln574_reg_167.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_local_in_V_read = ap_const_logic_1;
    } else {
        fifo_C_drain_local_in_V_read = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_icmp_ln574_fu_111_p2() {
    icmp_ln574_fu_111_p2 = (!indvar_flatten_reg_89.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_89.read() == ap_const_lv3_4);
}

void C_drain_IO_L1_out_in::thread_icmp_ln576_fu_123_p2() {
    icmp_ln576_fu_123_p2 = (!c7_0_reg_100.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c7_0_reg_100.read() == ap_const_lv2_2);
}

void C_drain_IO_L1_out_in::thread_local_C_0_V_address0() {
    local_C_0_V_address0 =  (sc_lv<1>) (zext_ln584_fu_137_p1.read());
}

void C_drain_IO_L1_out_in::thread_local_C_0_V_address1() {
    local_C_0_V_address1 = local_C_0_V_addr_reg_176.read();
}

void C_drain_IO_L1_out_in::thread_local_C_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        local_C_0_V_ce0 = ap_const_logic_1;
    } else {
        local_C_0_V_ce0 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_local_C_0_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        local_C_0_V_ce1 = ap_const_logic_1;
    } else {
        local_C_0_V_ce1 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_local_C_0_V_d1() {
    local_C_0_V_d1 = esl_concat<32,32>(fifo_C_drain_local_in_V_dout.read(), buf_data_split_1_V_fu_148_p4.read());
}

void C_drain_IO_L1_out_in::thread_local_C_0_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln574_reg_167.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        local_C_0_V_we1 = ap_const_logic_1;
    } else {
        local_C_0_V_we1 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_in::thread_select_ln576_fu_129_p3() {
    select_ln576_fu_129_p3 = (!icmp_ln576_fu_123_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln576_fu_123_p2.read()[0].to_bool())? ap_const_lv2_0: c7_0_reg_100.read());
}

void C_drain_IO_L1_out_in::thread_zext_ln584_fu_137_p1() {
    zext_ln584_fu_137_p1 = esl_zext<64,2>(select_ln576_fu_129_p3.read());
}

void C_drain_IO_L1_out_in::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln574_fu_111_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln574_fu_111_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

