// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "C_drain_IO_L1_out_he_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic C_drain_IO_L1_out_he_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic C_drain_IO_L1_out_he_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> C_drain_IO_L1_out_he_1::ap_ST_fsm_state1 = "1";
const sc_lv<5> C_drain_IO_L1_out_he_1::ap_ST_fsm_state2 = "10";
const sc_lv<5> C_drain_IO_L1_out_he_1::ap_ST_fsm_state3 = "100";
const sc_lv<5> C_drain_IO_L1_out_he_1::ap_ST_fsm_state4 = "1000";
const sc_lv<5> C_drain_IO_L1_out_he_1::ap_ST_fsm_state5 = "10000";
const sc_lv<32> C_drain_IO_L1_out_he_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> C_drain_IO_L1_out_he_1::ap_const_lv32_1 = "1";
const sc_lv<1> C_drain_IO_L1_out_he_1::ap_const_lv1_1 = "1";
const sc_lv<32> C_drain_IO_L1_out_he_1::ap_const_lv32_2 = "10";
const sc_lv<1> C_drain_IO_L1_out_he_1::ap_const_lv1_0 = "0";
const sc_lv<32> C_drain_IO_L1_out_he_1::ap_const_lv32_3 = "11";
const bool C_drain_IO_L1_out_he_1::ap_const_boolean_0 = false;
const sc_lv<2> C_drain_IO_L1_out_he_1::ap_const_lv2_0 = "00";
const sc_lv<32> C_drain_IO_L1_out_he_1::ap_const_lv32_4 = "100";
const sc_lv<2> C_drain_IO_L1_out_he_1::ap_const_lv2_2 = "10";
const sc_lv<2> C_drain_IO_L1_out_he_1::ap_const_lv2_1 = "1";
const bool C_drain_IO_L1_out_he_1::ap_const_boolean_1 = true;

C_drain_IO_L1_out_he_1::C_drain_IO_L1_out_he_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    local_C_ping_0_V_U = new C_drain_IO_L1_outncg("local_C_ping_0_V_U");
    local_C_ping_0_V_U->clk(ap_clk);
    local_C_ping_0_V_U->reset(ap_rst);
    local_C_ping_0_V_U->address0(local_C_ping_0_V_address0);
    local_C_ping_0_V_U->ce0(local_C_ping_0_V_ce0);
    local_C_ping_0_V_U->q0(local_C_ping_0_V_q0);
    local_C_ping_0_V_U->address1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address1);
    local_C_ping_0_V_U->ce1(local_C_ping_0_V_ce1);
    local_C_ping_0_V_U->we1(local_C_ping_0_V_we1);
    local_C_ping_0_V_U->d1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_d1);
    local_C_pong_0_V_U = new C_drain_IO_L1_outncg("local_C_pong_0_V_U");
    local_C_pong_0_V_U->clk(ap_clk);
    local_C_pong_0_V_U->reset(ap_rst);
    local_C_pong_0_V_U->address0(local_C_pong_0_V_address0);
    local_C_pong_0_V_U->ce0(local_C_pong_0_V_ce0);
    local_C_pong_0_V_U->q0(local_C_pong_0_V_q0);
    local_C_pong_0_V_U->address1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address1);
    local_C_pong_0_V_U->ce1(local_C_pong_0_V_ce1);
    local_C_pong_0_V_U->we1(local_C_pong_0_V_we1);
    local_C_pong_0_V_U->d1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_d1);
    grp_C_drain_IO_L1_out_in_fu_106 = new C_drain_IO_L1_out_in("grp_C_drain_IO_L1_out_in_fu_106");
    grp_C_drain_IO_L1_out_in_fu_106->ap_clk(ap_clk);
    grp_C_drain_IO_L1_out_in_fu_106->ap_rst(ap_rst);
    grp_C_drain_IO_L1_out_in_fu_106->ap_start(grp_C_drain_IO_L1_out_in_fu_106_ap_start);
    grp_C_drain_IO_L1_out_in_fu_106->ap_done(grp_C_drain_IO_L1_out_in_fu_106_ap_done);
    grp_C_drain_IO_L1_out_in_fu_106->ap_idle(grp_C_drain_IO_L1_out_in_fu_106_ap_idle);
    grp_C_drain_IO_L1_out_in_fu_106->ap_ready(grp_C_drain_IO_L1_out_in_fu_106_ap_ready);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_address0(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_ce0(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_q0(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_address1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address1);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_ce1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_we1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1);
    grp_C_drain_IO_L1_out_in_fu_106->local_C_0_V_d1(grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_d1);
    grp_C_drain_IO_L1_out_in_fu_106->fifo_C_drain_local_in_V_dout(fifo_C_drain_local_in_V_dout);
    grp_C_drain_IO_L1_out_in_fu_106->fifo_C_drain_local_in_V_empty_n(fifo_C_drain_local_in_V_empty_n);
    grp_C_drain_IO_L1_out_in_fu_106->fifo_C_drain_local_in_V_read(grp_C_drain_IO_L1_out_in_fu_106_fifo_C_drain_local_in_V_read);
    grp_C_drain_IO_L1_out_in_1_fu_113 = new C_drain_IO_L1_out_in_1("grp_C_drain_IO_L1_out_in_1_fu_113");
    grp_C_drain_IO_L1_out_in_1_fu_113->ap_clk(ap_clk);
    grp_C_drain_IO_L1_out_in_1_fu_113->ap_rst(ap_rst);
    grp_C_drain_IO_L1_out_in_1_fu_113->ap_start(grp_C_drain_IO_L1_out_in_1_fu_113_ap_start);
    grp_C_drain_IO_L1_out_in_1_fu_113->ap_done(grp_C_drain_IO_L1_out_in_1_fu_113_ap_done);
    grp_C_drain_IO_L1_out_in_1_fu_113->ap_idle(grp_C_drain_IO_L1_out_in_1_fu_113_ap_idle);
    grp_C_drain_IO_L1_out_in_1_fu_113->ap_ready(grp_C_drain_IO_L1_out_in_1_fu_113_ap_ready);
    grp_C_drain_IO_L1_out_in_1_fu_113->local_C_0_V_address0(grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0);
    grp_C_drain_IO_L1_out_in_1_fu_113->local_C_0_V_ce0(grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0);
    grp_C_drain_IO_L1_out_in_1_fu_113->local_C_0_V_q0(grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0);
    grp_C_drain_IO_L1_out_in_1_fu_113->fifo_C_drain_out_V_V_din(grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_din);
    grp_C_drain_IO_L1_out_in_1_fu_113->fifo_C_drain_out_V_V_full_n(fifo_C_drain_out_V_V_full_n);
    grp_C_drain_IO_L1_out_in_1_fu_113->fifo_C_drain_out_V_V_write(grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_write);
    grp_C_drain_IO_L1_out_in_1_fu_113->en(grp_C_drain_IO_L1_out_in_1_fu_113_en);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state4_on_subcall_done);
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_ap_done );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_ap_done );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_arb_1_phi_fu_87_p4);
    sensitive << ( arb_1_reg_83 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_ap_done );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_c0_fu_136_p2);
    sensitive << ( c0_prev_reg_72 );

    SC_METHOD(thread_c1_fu_148_p2);
    sensitive << ( c1_prev_reg_95 );

    SC_METHOD(thread_fifo_C_drain_local_in_V_read);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_fifo_C_drain_local_in_V_read );

    SC_METHOD(thread_fifo_C_drain_out_V_V_din);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_din );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fifo_C_drain_out_V_V_write);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_write );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_C_drain_IO_L1_out_in_1_fu_113_ap_start);
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg );

    SC_METHOD(thread_grp_C_drain_IO_L1_out_in_1_fu_113_en);
    sensitive << ( inter_trans_en_0_loa_1_reg_180 );
    sensitive << ( inter_trans_en_0_loa_reg_193 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( local_C_ping_0_V_q0 );
    sensitive << ( local_C_pong_0_V_q0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_C_drain_IO_L1_out_in_fu_106_ap_start);
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg );

    SC_METHOD(thread_grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( local_C_ping_0_V_q0 );
    sensitive << ( local_C_pong_0_V_q0 );

    SC_METHOD(thread_icmp_ln664_fu_130_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( c0_prev_reg_72 );

    SC_METHOD(thread_icmp_ln665_fu_142_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c1_prev_reg_95 );

    SC_METHOD(thread_local_C_ping_0_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0 );

    SC_METHOD(thread_local_C_ping_0_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0 );

    SC_METHOD(thread_local_C_ping_0_V_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1 );

    SC_METHOD(thread_local_C_ping_0_V_we1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1 );

    SC_METHOD(thread_local_C_pong_0_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_local_C_pong_0_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_local_C_pong_0_V_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1 );

    SC_METHOD(thread_local_C_pong_0_V_we1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( arb_1_reg_83 );
    sensitive << ( grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1 );

    SC_METHOD(thread_xor_ln678_fu_154_p2);
    sensitive << ( arb_1_reg_83 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln664_fu_130_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln665_fu_142_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_C_drain_IO_L1_out_in_1_fu_113_ap_done );
    sensitive << ( ap_block_state4_on_subcall_done );
    sensitive << ( ap_CS_fsm_state5 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00001";
    grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg = SC_LOGIC_0;
    grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "C_drain_IO_L1_out_he_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_din, "(port)fifo_C_drain_out_V_V_din");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_full_n, "(port)fifo_C_drain_out_V_V_full_n");
    sc_trace(mVcdFile, fifo_C_drain_out_V_V_write, "(port)fifo_C_drain_out_V_V_write");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_dout, "(port)fifo_C_drain_local_in_V_dout");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_empty_n, "(port)fifo_C_drain_local_in_V_empty_n");
    sc_trace(mVcdFile, fifo_C_drain_local_in_V_read, "(port)fifo_C_drain_local_in_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, c0_fu_136_p2, "c0_fu_136_p2");
    sc_trace(mVcdFile, c0_reg_175, "c0_reg_175");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, inter_trans_en_0_loa_1_reg_180, "inter_trans_en_0_loa_1_reg_180");
    sc_trace(mVcdFile, icmp_ln664_fu_130_p2, "icmp_ln664_fu_130_p2");
    sc_trace(mVcdFile, c1_fu_148_p2, "c1_fu_148_p2");
    sc_trace(mVcdFile, c1_reg_188, "c1_reg_188");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, inter_trans_en_0_loa_reg_193, "inter_trans_en_0_loa_reg_193");
    sc_trace(mVcdFile, icmp_ln665_fu_142_p2, "icmp_ln665_fu_142_p2");
    sc_trace(mVcdFile, xor_ln678_fu_154_p2, "xor_ln678_fu_154_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_ap_ready, "grp_C_drain_IO_L1_out_in_fu_106_ap_ready");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_ap_done, "grp_C_drain_IO_L1_out_in_fu_106_ap_done");
    sc_trace(mVcdFile, arb_1_reg_83, "arb_1_reg_83");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_ap_ready, "grp_C_drain_IO_L1_out_in_1_fu_113_ap_ready");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_ap_done, "grp_C_drain_IO_L1_out_in_1_fu_113_ap_done");
    sc_trace(mVcdFile, ap_block_state4_on_subcall_done, "ap_block_state4_on_subcall_done");
    sc_trace(mVcdFile, local_C_ping_0_V_address0, "local_C_ping_0_V_address0");
    sc_trace(mVcdFile, local_C_ping_0_V_ce0, "local_C_ping_0_V_ce0");
    sc_trace(mVcdFile, local_C_ping_0_V_q0, "local_C_ping_0_V_q0");
    sc_trace(mVcdFile, local_C_ping_0_V_ce1, "local_C_ping_0_V_ce1");
    sc_trace(mVcdFile, local_C_ping_0_V_we1, "local_C_ping_0_V_we1");
    sc_trace(mVcdFile, local_C_pong_0_V_address0, "local_C_pong_0_V_address0");
    sc_trace(mVcdFile, local_C_pong_0_V_ce0, "local_C_pong_0_V_ce0");
    sc_trace(mVcdFile, local_C_pong_0_V_q0, "local_C_pong_0_V_q0");
    sc_trace(mVcdFile, local_C_pong_0_V_ce1, "local_C_pong_0_V_ce1");
    sc_trace(mVcdFile, local_C_pong_0_V_we1, "local_C_pong_0_V_we1");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_ap_start, "grp_C_drain_IO_L1_out_in_fu_106_ap_start");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_ap_idle, "grp_C_drain_IO_L1_out_in_fu_106_ap_idle");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address1, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address1");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_d1, "grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_d1");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_fifo_C_drain_local_in_V_read, "grp_C_drain_IO_L1_out_in_fu_106_fifo_C_drain_local_in_V_read");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_ap_start, "grp_C_drain_IO_L1_out_in_1_fu_113_ap_start");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_ap_idle, "grp_C_drain_IO_L1_out_in_1_fu_113_ap_idle");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0, "grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0, "grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0, "grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_din, "grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_din");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_write, "grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_write");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_en, "grp_C_drain_IO_L1_out_in_1_fu_113_en");
    sc_trace(mVcdFile, c0_prev_reg_72, "c0_prev_reg_72");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_phi_mux_arb_1_phi_fu_87_p4, "ap_phi_mux_arb_1_phi_fu_87_p4");
    sc_trace(mVcdFile, c1_prev_reg_95, "c1_prev_reg_95");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg, "grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg");
    sc_trace(mVcdFile, grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg, "grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, inter_trans_en_0_fu_60, "inter_trans_en_0_fu_60");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

C_drain_IO_L1_out_he_1::~C_drain_IO_L1_out_he_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete local_C_ping_0_V_U;
    delete local_C_pong_0_V_U;
    delete grp_C_drain_IO_L1_out_in_fu_106;
    delete grp_C_drain_IO_L1_out_in_1_fu_113;
}

void C_drain_IO_L1_out_he_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                    esl_seteq<1,1,1>(grp_C_drain_IO_L1_out_in_1_fu_113_ap_done.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln664_fu_130_p2.read(), ap_const_lv1_0))) {
        arb_1_reg_83 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        arb_1_reg_83 = xor_ln678_fu_154_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln665_fu_142_p2.read()))) {
        c0_prev_reg_72 = c0_reg_175.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        c0_prev_reg_72 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln664_fu_130_p2.read(), ap_const_lv1_0))) {
        c1_prev_reg_95 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        c1_prev_reg_95 = c1_reg_188.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
              esl_seteq<1,1,1>(icmp_ln664_fu_130_p2.read(), ap_const_lv1_1)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
              esl_seteq<1,1,1>(icmp_ln665_fu_142_p2.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, ap_phi_mux_arb_1_phi_fu_87_p4.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
              esl_seteq<1,1,1>(icmp_ln665_fu_142_p2.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_arb_1_phi_fu_87_p4.read())))) {
            grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_C_drain_IO_L1_out_in_1_fu_113_ap_ready.read())) {
            grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
              esl_seteq<1,1,1>(icmp_ln665_fu_142_p2.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, ap_phi_mux_arb_1_phi_fu_87_p4.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
              esl_seteq<1,1,1>(icmp_ln665_fu_142_p2.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_arb_1_phi_fu_87_p4.read())))) {
            grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_C_drain_IO_L1_out_in_fu_106_ap_ready.read())) {
            grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        inter_trans_en_0_fu_60 = ap_const_lv1_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        inter_trans_en_0_fu_60 = ap_const_lv1_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c0_reg_175 = c0_fu_136_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c1_reg_188 = c1_fu_148_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln664_fu_130_p2.read(), ap_const_lv1_1))) {
        inter_trans_en_0_loa_1_reg_180 = inter_trans_en_0_fu_60.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln665_fu_142_p2.read(), ap_const_lv1_0))) {
        inter_trans_en_0_loa_reg_193 = inter_trans_en_0_fu_60.read();
    }
}

void C_drain_IO_L1_out_he_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void C_drain_IO_L1_out_he_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void C_drain_IO_L1_out_he_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void C_drain_IO_L1_out_he_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void C_drain_IO_L1_out_he_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void C_drain_IO_L1_out_he_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void C_drain_IO_L1_out_he_1::thread_ap_block_state4_on_subcall_done() {
    ap_block_state4_on_subcall_done = ((esl_seteq<1,1,1>(ap_const_logic_0, grp_C_drain_IO_L1_out_in_fu_106_ap_done.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_C_drain_IO_L1_out_in_1_fu_113_ap_done.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, grp_C_drain_IO_L1_out_in_fu_106_ap_done.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, grp_C_drain_IO_L1_out_in_1_fu_113_ap_done.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())));
}

void C_drain_IO_L1_out_he_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(grp_C_drain_IO_L1_out_in_1_fu_113_ap_done.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void C_drain_IO_L1_out_he_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_ap_phi_mux_arb_1_phi_fu_87_p4() {
    ap_phi_mux_arb_1_phi_fu_87_p4 = arb_1_reg_83.read();
}

void C_drain_IO_L1_out_he_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(grp_C_drain_IO_L1_out_in_1_fu_113_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_c0_fu_136_p2() {
    c0_fu_136_p2 = (!c0_prev_reg_72.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c0_prev_reg_72.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void C_drain_IO_L1_out_he_1::thread_c1_fu_148_p2() {
    c1_fu_148_p2 = (!c1_prev_reg_95.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c1_prev_reg_95.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void C_drain_IO_L1_out_he_1::thread_fifo_C_drain_local_in_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())))) {
        fifo_C_drain_local_in_V_read = grp_C_drain_IO_L1_out_in_fu_106_fifo_C_drain_local_in_V_read.read();
    } else {
        fifo_C_drain_local_in_V_read = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_fifo_C_drain_out_V_V_din() {
    fifo_C_drain_out_V_V_din = grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_din.read();
}

void C_drain_IO_L1_out_he_1::thread_fifo_C_drain_out_V_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        fifo_C_drain_out_V_V_write = grp_C_drain_IO_L1_out_in_1_fu_113_fifo_C_drain_out_V_V_write.read();
    } else {
        fifo_C_drain_out_V_V_write = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_grp_C_drain_IO_L1_out_in_1_fu_113_ap_start() {
    grp_C_drain_IO_L1_out_in_1_fu_113_ap_start = grp_C_drain_IO_L1_out_in_1_fu_113_ap_start_reg.read();
}

void C_drain_IO_L1_out_he_1::thread_grp_C_drain_IO_L1_out_in_1_fu_113_en() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())))) {
        grp_C_drain_IO_L1_out_in_1_fu_113_en =  (sc_logic) (inter_trans_en_0_loa_reg_193.read()[0]);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_C_drain_IO_L1_out_in_1_fu_113_en =  (sc_logic) (inter_trans_en_0_loa_1_reg_180.read()[0]);
    } else {
        grp_C_drain_IO_L1_out_in_1_fu_113_en = sc_logic('X');
    }
}

void C_drain_IO_L1_out_he_1::thread_grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read()))) {
        grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0 = local_C_ping_0_V_q0.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0 = local_C_pong_0_V_q0.read();
    } else {
        grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void C_drain_IO_L1_out_he_1::thread_grp_C_drain_IO_L1_out_in_fu_106_ap_start() {
    grp_C_drain_IO_L1_out_in_fu_106_ap_start = grp_C_drain_IO_L1_out_in_fu_106_ap_start_reg.read();
}

void C_drain_IO_L1_out_he_1::thread_grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())) {
            grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0 = local_C_pong_0_V_q0.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) {
            grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0 = local_C_ping_0_V_q0.read();
        } else {
            grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void C_drain_IO_L1_out_he_1::thread_icmp_ln664_fu_130_p2() {
    icmp_ln664_fu_130_p2 = (!c0_prev_reg_72.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c0_prev_reg_72.read() == ap_const_lv2_2);
}

void C_drain_IO_L1_out_he_1::thread_icmp_ln665_fu_142_p2() {
    icmp_ln665_fu_142_p2 = (!c1_prev_reg_95.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c1_prev_reg_95.read() == ap_const_lv2_2);
}

void C_drain_IO_L1_out_he_1::thread_local_C_ping_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())) {
            local_C_ping_0_V_address0 = grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) {
            local_C_ping_0_V_address0 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0.read();
        } else {
            local_C_ping_0_V_address0 =  (sc_lv<1>) ("X");
        }
    } else {
        local_C_ping_0_V_address0 =  (sc_lv<1>) ("X");
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_ping_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read())) {
            local_C_ping_0_V_ce0 = grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) {
            local_C_ping_0_V_ce0 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0.read();
        } else {
            local_C_ping_0_V_ce0 = ap_const_logic_0;
        }
    } else {
        local_C_ping_0_V_ce0 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_ping_0_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read()))) {
        local_C_ping_0_V_ce1 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1.read();
    } else {
        local_C_ping_0_V_ce1 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_ping_0_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read()))) {
        local_C_ping_0_V_we1 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1.read();
    } else {
        local_C_ping_0_V_we1 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_pong_0_V_address0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        local_C_pong_0_V_address0 = grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read()))) {
        local_C_pong_0_V_address0 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_address0.read();
    } else {
        local_C_pong_0_V_address0 =  (sc_lv<1>) ("X");
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_pong_0_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, arb_1_reg_83.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        local_C_pong_0_V_ce0 = grp_C_drain_IO_L1_out_in_1_fu_113_local_C_0_V_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read()))) {
        local_C_pong_0_V_ce0 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce0.read();
    } else {
        local_C_pong_0_V_ce0 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_pong_0_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read()))) {
        local_C_pong_0_V_ce1 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_ce1.read();
    } else {
        local_C_pong_0_V_ce1 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_local_C_pong_0_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, arb_1_reg_83.read()))) {
        local_C_pong_0_V_we1 = grp_C_drain_IO_L1_out_in_fu_106_local_C_0_V_we1.read();
    } else {
        local_C_pong_0_V_we1 = ap_const_logic_0;
    }
}

void C_drain_IO_L1_out_he_1::thread_xor_ln678_fu_154_p2() {
    xor_ln678_fu_154_p2 = (arb_1_reg_83.read() ^ ap_const_lv1_1);
}

void C_drain_IO_L1_out_he_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln664_fu_130_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln665_fu_142_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(grp_C_drain_IO_L1_out_in_1_fu_113_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

