// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "PE.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic PE::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic PE::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> PE::ap_ST_fsm_state1 = "1";
const sc_lv<6> PE::ap_ST_fsm_state2 = "10";
const sc_lv<6> PE::ap_ST_fsm_state3 = "100";
const sc_lv<6> PE::ap_ST_fsm_state4 = "1000";
const sc_lv<6> PE::ap_ST_fsm_pp1_stage0 = "10000";
const sc_lv<6> PE::ap_ST_fsm_state9 = "100000";
const bool PE::ap_const_boolean_1 = true;
const sc_lv<32> PE::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> PE::ap_const_lv32_4 = "100";
const bool PE::ap_const_boolean_0 = false;
const sc_lv<1> PE::ap_const_lv1_0 = "0";
const sc_lv<1> PE::ap_const_lv1_1 = "1";
const sc_lv<32> PE::ap_const_lv32_1 = "1";
const sc_lv<32> PE::ap_const_lv32_2 = "10";
const sc_lv<32> PE::ap_const_lv32_3 = "11";
const sc_lv<3> PE::ap_const_lv3_0 = "000";
const sc_lv<32> PE::ap_const_lv32_5 = "101";
const sc_lv<2> PE::ap_const_lv2_0 = "00";
const sc_lv<5> PE::ap_const_lv5_0 = "00000";
const sc_lv<4> PE::ap_const_lv4_0 = "0000";
const sc_lv<3> PE::ap_const_lv3_4 = "100";
const sc_lv<3> PE::ap_const_lv3_1 = "1";
const sc_lv<2> PE::ap_const_lv2_1 = "1";
const sc_lv<2> PE::ap_const_lv2_2 = "10";
const sc_lv<5> PE::ap_const_lv5_10 = "10000";
const sc_lv<5> PE::ap_const_lv5_1 = "1";
const sc_lv<5> PE::ap_const_lv5_8 = "1000";
const sc_lv<4> PE::ap_const_lv4_4 = "100";
const sc_lv<4> PE::ap_const_lv4_1 = "1";
const sc_lv<32> PE::ap_const_lv32_20 = "100000";
const sc_lv<32> PE::ap_const_lv32_3F = "111111";

PE::PE(sc_module_name name) : sc_module(name), mVcdFile(0) {
    local_C_U = new PE139_local_C("local_C_U");
    local_C_U->clk(ap_clk);
    local_C_U->reset(ap_rst);
    local_C_U->address0(local_C_address0);
    local_C_U->ce0(local_C_ce0);
    local_C_U->we0(local_C_we0);
    local_C_U->d0(ap_var_for_const0);
    local_C_U->q0(local_C_q0);
    local_C_U->address1(local_C_addr_4_reg_827_pp1_iter2_reg);
    local_C_U->ce1(local_C_ce1);
    local_C_U->we1(local_C_we1);
    local_C_U->d1(tmp_5_fu_723_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln435_fu_337_p2);
    sensitive << ( indvar_flatten53_reg_210 );

    SC_METHOD(thread_add_ln440_fu_349_p2);
    sensitive << ( indvar_flatten_reg_221 );

    SC_METHOD(thread_add_ln446_fu_399_p2);
    sensitive << ( zext_ln442_fu_383_p1 );
    sensitive << ( zext_ln446_fu_395_p1 );

    SC_METHOD(thread_add_ln449_fu_440_p2);
    sensitive << ( indvar_flatten46_reg_254 );

    SC_METHOD(thread_add_ln452_4_fu_644_p2);
    sensitive << ( indvar_flatten20_reg_276 );

    SC_METHOD(thread_add_ln454_4_fu_630_p2);
    sensitive << ( indvar_flatten6_reg_298 );

    SC_METHOD(thread_add_ln479_7_fu_700_p2);
    sensitive << ( zext_ln479_7_fu_696_p1 );
    sensitive << ( zext_ln479_fu_658_p1 );

    SC_METHOD(thread_add_ln479_fu_719_p2);
    sensitive << ( mul_ln479_reg_833 );
    sensitive << ( mul_ln479_1_reg_838 );

    SC_METHOD(thread_and_ln480_16_fu_486_p2);
    sensitive << ( and_ln480_fu_428_p2 );
    sensitive << ( xor_ln480_fu_480_p2 );

    SC_METHOD(thread_and_ln480_17_fu_498_p2);
    sensitive << ( xor_ln480_fu_480_p2 );
    sensitive << ( icmp_ln456_fu_492_p2 );

    SC_METHOD(thread_and_ln480_18_fu_510_p2);
    sensitive << ( xor_ln480_fu_480_p2 );
    sensitive << ( icmp_ln454_fu_504_p2 );

    SC_METHOD(thread_and_ln480_19_fu_550_p2);
    sensitive << ( select_ln480_10_fu_472_p3 );
    sensitive << ( icmp_ln480_9_fu_544_p2 );

    SC_METHOD(thread_and_ln480_20_fu_576_p2);
    sensitive << ( and_ln480_17_fu_498_p2 );
    sensitive << ( or_ln480_4_fu_570_p2 );

    SC_METHOD(thread_and_ln480_fu_428_p2);
    sensitive << ( icmp_ln480_fu_416_p2 );
    sensitive << ( icmp_ln480_1_fu_422_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( fifo_A_in_V_V_empty_n );
    sensitive << ( fifo_A_out_V_V_full_n );
    sensitive << ( fifo_B_in_V_V_empty_n );
    sensitive << ( fifo_B_out_V_V_full_n );
    sensitive << ( fifo_C_drain_out_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( fifo_A_in_V_V_empty_n );
    sensitive << ( fifo_A_out_V_V_full_n );
    sensitive << ( fifo_B_in_V_V_empty_n );
    sensitive << ( fifo_B_out_V_V_full_n );
    sensitive << ( fifo_C_drain_out_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( fifo_A_in_V_V_empty_n );
    sensitive << ( fifo_A_out_V_V_full_n );
    sensitive << ( fifo_B_in_V_V_empty_n );
    sensitive << ( fifo_B_out_V_V_full_n );
    sensitive << ( fifo_C_drain_out_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter1);
    sensitive << ( fifo_A_in_V_V_empty_n );
    sensitive << ( fifo_A_out_V_V_full_n );
    sensitive << ( fifo_B_in_V_V_empty_n );
    sensitive << ( fifo_B_out_V_V_full_n );
    sensitive << ( icmp_ln449_reg_758 );

    SC_METHOD(thread_ap_block_state7_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp1_stage0_iter3);
    sensitive << ( fifo_C_drain_out_V_full_n );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state5);
    sensitive << ( icmp_ln449_fu_434_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln435_fu_331_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_ap_phi_mux_c61_0_phi_fu_313_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( c61_0_reg_309 );
    sensitive << ( select_ln479_4_reg_786 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_c2_fu_446_p2);
    sensitive << ( c2_0_reg_265 );

    SC_METHOD(thread_c5_fu_524_p2);
    sensitive << ( select_ln480_fu_458_p3 );

    SC_METHOD(thread_c6_6_fu_590_p2);
    sensitive << ( select_ln480_11_fu_536_p3 );

    SC_METHOD(thread_c6_fu_355_p2);
    sensitive << ( c6_0_reg_232 );

    SC_METHOD(thread_c7_4_fu_624_p2);
    sensitive << ( select_ln479_fu_608_p3 );

    SC_METHOD(thread_c7_fu_410_p2);
    sensitive << ( select_ln446_fu_367_p3 );

    SC_METHOD(thread_fifo_A_in_V_V_blk_n);
    sensitive << ( fifo_A_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln449_reg_758 );

    SC_METHOD(thread_fifo_A_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_fifo_A_out_V_V_blk_n);
    sensitive << ( fifo_A_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln449_reg_758 );

    SC_METHOD(thread_fifo_A_out_V_V_din);
    sensitive << ( fifo_A_in_V_V_dout );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_fifo_A_out_V_V_write);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_fifo_B_in_V_V_blk_n);
    sensitive << ( fifo_B_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln449_reg_758 );

    SC_METHOD(thread_fifo_B_in_V_V_read);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_fifo_B_out_V_V_blk_n);
    sensitive << ( fifo_B_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln449_reg_758 );

    SC_METHOD(thread_fifo_B_out_V_V_din);
    sensitive << ( fifo_B_in_V_V_dout );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_fifo_B_out_V_V_write);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln449_reg_758 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_fifo_C_drain_out_V_blk_n);
    sensitive << ( fifo_C_drain_out_V_full_n );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );

    SC_METHOD(thread_fifo_C_drain_out_V_din);
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );
    sensitive << ( ap_block_pp1_stage0_01001 );
    sensitive << ( tmp_5_fu_723_p2 );

    SC_METHOD(thread_fifo_C_drain_out_V_write);
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( select_ln480_12_reg_772_pp1_iter2_reg );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_icmp_ln435_fu_331_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten53_reg_210 );

    SC_METHOD(thread_icmp_ln440_fu_343_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( indvar_flatten_reg_221 );

    SC_METHOD(thread_icmp_ln442_fu_361_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln440_fu_343_p2 );
    sensitive << ( c7_0_reg_243 );

    SC_METHOD(thread_icmp_ln449_fu_434_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( indvar_flatten46_reg_254 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln452_fu_452_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( indvar_flatten20_reg_276 );
    sensitive << ( icmp_ln449_fu_434_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln454_fu_504_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( indvar_flatten6_reg_298 );
    sensitive << ( icmp_ln449_fu_434_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln456_fu_492_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( c72_0_reg_320 );
    sensitive << ( icmp_ln449_fu_434_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln480_1_fu_422_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( c5_0_reg_287 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln480_8_fu_466_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( c2_0_reg_265 );
    sensitive << ( icmp_ln449_fu_434_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln480_9_fu_544_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( icmp_ln449_fu_434_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( select_ln480_fu_458_p3 );

    SC_METHOD(thread_icmp_ln480_fu_416_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( c2_0_reg_265 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln435_fu_331_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_local_C_address0);
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( local_C_addr_4_reg_827 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( zext_ln446_4_fu_405_p1 );

    SC_METHOD(thread_local_C_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_local_C_ce1);
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_local_C_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln440_fu_343_p2 );

    SC_METHOD(thread_local_C_we1);
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( icmp_ln449_reg_758_pp1_iter2_reg );

    SC_METHOD(thread_mul_ln479_1_fu_715_p2);
    sensitive << ( p_Repl2_12_reg_812 );
    sensitive << ( p_Repl2_10_reg_822 );

    SC_METHOD(thread_mul_ln479_fu_711_p2);
    sensitive << ( p_Repl2_11_reg_807 );
    sensitive << ( p_Repl2_s_reg_817 );

    SC_METHOD(thread_or_ln479_4_fu_602_p2);
    sensitive << ( icmp_ln452_fu_452_p2 );
    sensitive << ( or_ln479_fu_596_p2 );

    SC_METHOD(thread_or_ln479_fu_596_p2);
    sensitive << ( and_ln480_18_fu_510_p2 );
    sensitive << ( and_ln480_20_fu_576_p2 );

    SC_METHOD(thread_or_ln480_4_fu_570_p2);
    sensitive << ( icmp_ln452_fu_452_p2 );
    sensitive << ( xor_ln480_4_fu_564_p2 );

    SC_METHOD(thread_or_ln480_fu_530_p2);
    sensitive << ( icmp_ln452_fu_452_p2 );
    sensitive << ( and_ln480_18_fu_510_p2 );

    SC_METHOD(thread_p_Repl2_11_fu_661_p1);
    sensitive << ( fifo_A_in_V_V_dout );

    SC_METHOD(thread_p_Repl2_s_fu_675_p1);
    sensitive << ( fifo_B_in_V_V_dout );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_select_ln446_4_fu_375_p3);
    sensitive << ( c6_0_reg_232 );
    sensitive << ( icmp_ln442_fu_361_p2 );
    sensitive << ( c6_fu_355_p2 );

    SC_METHOD(thread_select_ln446_fu_367_p3);
    sensitive << ( c7_0_reg_243 );
    sensitive << ( icmp_ln442_fu_361_p2 );

    SC_METHOD(thread_select_ln449_fu_516_p3);
    sensitive << ( c2_0_reg_265 );
    sensitive << ( icmp_ln452_fu_452_p2 );
    sensitive << ( c2_fu_446_p2 );

    SC_METHOD(thread_select_ln452_4_fu_650_p3);
    sensitive << ( icmp_ln452_fu_452_p2 );
    sensitive << ( add_ln452_4_fu_644_p2 );

    SC_METHOD(thread_select_ln452_fu_582_p3);
    sensitive << ( select_ln480_fu_458_p3 );
    sensitive << ( and_ln480_18_fu_510_p2 );
    sensitive << ( c5_fu_524_p2 );

    SC_METHOD(thread_select_ln454_fu_636_p3);
    sensitive << ( or_ln480_fu_530_p2 );
    sensitive << ( add_ln454_4_fu_630_p2 );

    SC_METHOD(thread_select_ln479_4_fu_616_p3);
    sensitive << ( select_ln480_11_fu_536_p3 );
    sensitive << ( and_ln480_20_fu_576_p2 );
    sensitive << ( c6_6_fu_590_p2 );

    SC_METHOD(thread_select_ln479_fu_608_p3);
    sensitive << ( c72_0_reg_320 );
    sensitive << ( or_ln479_4_fu_602_p2 );

    SC_METHOD(thread_select_ln480_10_fu_472_p3);
    sensitive << ( icmp_ln480_fu_416_p2 );
    sensitive << ( icmp_ln452_fu_452_p2 );
    sensitive << ( icmp_ln480_8_fu_466_p2 );

    SC_METHOD(thread_select_ln480_11_fu_536_p3);
    sensitive << ( ap_phi_mux_c61_0_phi_fu_313_p4 );
    sensitive << ( or_ln480_fu_530_p2 );

    SC_METHOD(thread_select_ln480_12_fu_556_p3);
    sensitive << ( and_ln480_18_fu_510_p2 );
    sensitive << ( and_ln480_19_fu_550_p2 );
    sensitive << ( and_ln480_16_fu_486_p2 );

    SC_METHOD(thread_select_ln480_fu_458_p3);
    sensitive << ( c5_0_reg_287 );
    sensitive << ( icmp_ln452_fu_452_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_2_fu_387_p3);
    sensitive << ( select_ln446_fu_367_p3 );

    SC_METHOD(thread_tmp_3_fu_689_p3);
    sensitive << ( select_ln479_reg_781 );

    SC_METHOD(thread_tmp_5_fu_723_p2);
    sensitive << ( local_C_q0 );
    sensitive << ( add_ln479_fu_719_p2 );

    SC_METHOD(thread_xor_ln480_4_fu_564_p2);
    sensitive << ( icmp_ln454_fu_504_p2 );

    SC_METHOD(thread_xor_ln480_fu_480_p2);
    sensitive << ( icmp_ln452_fu_452_p2 );

    SC_METHOD(thread_zext_ln442_fu_383_p1);
    sensitive << ( select_ln446_4_fu_375_p3 );

    SC_METHOD(thread_zext_ln446_4_fu_405_p1);
    sensitive << ( add_ln446_fu_399_p2 );

    SC_METHOD(thread_zext_ln446_fu_395_p1);
    sensitive << ( tmp_2_fu_387_p3 );

    SC_METHOD(thread_zext_ln479_7_fu_696_p1);
    sensitive << ( tmp_3_fu_689_p3 );

    SC_METHOD(thread_zext_ln479_8_fu_706_p1);
    sensitive << ( add_ln479_7_fu_700_p2 );

    SC_METHOD(thread_zext_ln479_fu_658_p1);
    sensitive << ( select_ln479_4_reg_786 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( icmp_ln435_fu_331_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln440_fu_343_p2 );
    sensitive << ( icmp_ln449_fu_434_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_THREAD(thread_ap_var_for_const0);

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000001";
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "PE_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, fifo_A_in_V_V_dout, "(port)fifo_A_in_V_V_dout");
    sc_trace(mVcdFile, fifo_A_in_V_V_empty_n, "(port)fifo_A_in_V_V_empty_n");
    sc_trace(mVcdFile, fifo_A_in_V_V_read, "(port)fifo_A_in_V_V_read");
    sc_trace(mVcdFile, fifo_A_out_V_V_din, "(port)fifo_A_out_V_V_din");
    sc_trace(mVcdFile, fifo_A_out_V_V_full_n, "(port)fifo_A_out_V_V_full_n");
    sc_trace(mVcdFile, fifo_A_out_V_V_write, "(port)fifo_A_out_V_V_write");
    sc_trace(mVcdFile, fifo_B_in_V_V_dout, "(port)fifo_B_in_V_V_dout");
    sc_trace(mVcdFile, fifo_B_in_V_V_empty_n, "(port)fifo_B_in_V_V_empty_n");
    sc_trace(mVcdFile, fifo_B_in_V_V_read, "(port)fifo_B_in_V_V_read");
    sc_trace(mVcdFile, fifo_B_out_V_V_din, "(port)fifo_B_out_V_V_din");
    sc_trace(mVcdFile, fifo_B_out_V_V_full_n, "(port)fifo_B_out_V_V_full_n");
    sc_trace(mVcdFile, fifo_B_out_V_V_write, "(port)fifo_B_out_V_V_write");
    sc_trace(mVcdFile, fifo_C_drain_out_V_din, "(port)fifo_C_drain_out_V_din");
    sc_trace(mVcdFile, fifo_C_drain_out_V_full_n, "(port)fifo_C_drain_out_V_full_n");
    sc_trace(mVcdFile, fifo_C_drain_out_V_write, "(port)fifo_C_drain_out_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, fifo_A_in_V_V_blk_n, "fifo_A_in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, icmp_ln449_reg_758, "icmp_ln449_reg_758");
    sc_trace(mVcdFile, fifo_A_out_V_V_blk_n, "fifo_A_out_V_V_blk_n");
    sc_trace(mVcdFile, fifo_B_in_V_V_blk_n, "fifo_B_in_V_V_blk_n");
    sc_trace(mVcdFile, fifo_B_out_V_V_blk_n, "fifo_B_out_V_V_blk_n");
    sc_trace(mVcdFile, fifo_C_drain_out_V_blk_n, "fifo_C_drain_out_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter3, "ap_enable_reg_pp1_iter3");
    sc_trace(mVcdFile, select_ln480_12_reg_772, "select_ln480_12_reg_772");
    sc_trace(mVcdFile, select_ln480_12_reg_772_pp1_iter2_reg, "select_ln480_12_reg_772_pp1_iter2_reg");
    sc_trace(mVcdFile, indvar_flatten46_reg_254, "indvar_flatten46_reg_254");
    sc_trace(mVcdFile, c2_0_reg_265, "c2_0_reg_265");
    sc_trace(mVcdFile, indvar_flatten20_reg_276, "indvar_flatten20_reg_276");
    sc_trace(mVcdFile, c5_0_reg_287, "c5_0_reg_287");
    sc_trace(mVcdFile, indvar_flatten6_reg_298, "indvar_flatten6_reg_298");
    sc_trace(mVcdFile, c61_0_reg_309, "c61_0_reg_309");
    sc_trace(mVcdFile, c72_0_reg_320, "c72_0_reg_320");
    sc_trace(mVcdFile, icmp_ln435_fu_331_p2, "icmp_ln435_fu_331_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln435_fu_337_p2, "add_ln435_fu_337_p2");
    sc_trace(mVcdFile, add_ln435_reg_735, "add_ln435_reg_735");
    sc_trace(mVcdFile, add_ln440_fu_349_p2, "add_ln440_fu_349_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, select_ln446_4_fu_375_p3, "select_ln446_4_fu_375_p3");
    sc_trace(mVcdFile, icmp_ln440_fu_343_p2, "icmp_ln440_fu_343_p2");
    sc_trace(mVcdFile, c7_fu_410_p2, "c7_fu_410_p2");
    sc_trace(mVcdFile, icmp_ln449_fu_434_p2, "icmp_ln449_fu_434_p2");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter0, "ap_block_state5_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter1, "ap_block_state6_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp1_stage0_iter2, "ap_block_state7_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp1_stage0_iter3, "ap_block_state8_pp1_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, icmp_ln449_reg_758_pp1_iter1_reg, "icmp_ln449_reg_758_pp1_iter1_reg");
    sc_trace(mVcdFile, icmp_ln449_reg_758_pp1_iter2_reg, "icmp_ln449_reg_758_pp1_iter2_reg");
    sc_trace(mVcdFile, add_ln449_fu_440_p2, "add_ln449_fu_440_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, select_ln449_fu_516_p3, "select_ln449_fu_516_p3");
    sc_trace(mVcdFile, select_ln480_12_fu_556_p3, "select_ln480_12_fu_556_p3");
    sc_trace(mVcdFile, select_ln480_12_reg_772_pp1_iter1_reg, "select_ln480_12_reg_772_pp1_iter1_reg");
    sc_trace(mVcdFile, select_ln452_fu_582_p3, "select_ln452_fu_582_p3");
    sc_trace(mVcdFile, select_ln479_fu_608_p3, "select_ln479_fu_608_p3");
    sc_trace(mVcdFile, select_ln479_reg_781, "select_ln479_reg_781");
    sc_trace(mVcdFile, select_ln479_4_fu_616_p3, "select_ln479_4_fu_616_p3");
    sc_trace(mVcdFile, select_ln479_4_reg_786, "select_ln479_4_reg_786");
    sc_trace(mVcdFile, c7_4_fu_624_p2, "c7_4_fu_624_p2");
    sc_trace(mVcdFile, select_ln454_fu_636_p3, "select_ln454_fu_636_p3");
    sc_trace(mVcdFile, select_ln452_4_fu_650_p3, "select_ln452_4_fu_650_p3");
    sc_trace(mVcdFile, p_Repl2_11_fu_661_p1, "p_Repl2_11_fu_661_p1");
    sc_trace(mVcdFile, p_Repl2_11_reg_807, "p_Repl2_11_reg_807");
    sc_trace(mVcdFile, p_Repl2_12_reg_812, "p_Repl2_12_reg_812");
    sc_trace(mVcdFile, p_Repl2_s_fu_675_p1, "p_Repl2_s_fu_675_p1");
    sc_trace(mVcdFile, p_Repl2_s_reg_817, "p_Repl2_s_reg_817");
    sc_trace(mVcdFile, p_Repl2_10_reg_822, "p_Repl2_10_reg_822");
    sc_trace(mVcdFile, local_C_addr_4_reg_827, "local_C_addr_4_reg_827");
    sc_trace(mVcdFile, local_C_addr_4_reg_827_pp1_iter2_reg, "local_C_addr_4_reg_827_pp1_iter2_reg");
    sc_trace(mVcdFile, mul_ln479_fu_711_p2, "mul_ln479_fu_711_p2");
    sc_trace(mVcdFile, mul_ln479_reg_833, "mul_ln479_reg_833");
    sc_trace(mVcdFile, mul_ln479_1_fu_715_p2, "mul_ln479_1_fu_715_p2");
    sc_trace(mVcdFile, mul_ln479_1_reg_838, "mul_ln479_1_reg_838");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state5, "ap_condition_pp1_exit_iter0_state5");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, local_C_address0, "local_C_address0");
    sc_trace(mVcdFile, local_C_ce0, "local_C_ce0");
    sc_trace(mVcdFile, local_C_we0, "local_C_we0");
    sc_trace(mVcdFile, local_C_q0, "local_C_q0");
    sc_trace(mVcdFile, local_C_ce1, "local_C_ce1");
    sc_trace(mVcdFile, local_C_we1, "local_C_we1");
    sc_trace(mVcdFile, indvar_flatten53_reg_210, "indvar_flatten53_reg_210");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, indvar_flatten_reg_221, "indvar_flatten_reg_221");
    sc_trace(mVcdFile, c6_0_reg_232, "c6_0_reg_232");
    sc_trace(mVcdFile, c7_0_reg_243, "c7_0_reg_243");
    sc_trace(mVcdFile, ap_phi_mux_c61_0_phi_fu_313_p4, "ap_phi_mux_c61_0_phi_fu_313_p4");
    sc_trace(mVcdFile, zext_ln446_4_fu_405_p1, "zext_ln446_4_fu_405_p1");
    sc_trace(mVcdFile, zext_ln479_8_fu_706_p1, "zext_ln479_8_fu_706_p1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, tmp_5_fu_723_p2, "tmp_5_fu_723_p2");
    sc_trace(mVcdFile, icmp_ln442_fu_361_p2, "icmp_ln442_fu_361_p2");
    sc_trace(mVcdFile, c6_fu_355_p2, "c6_fu_355_p2");
    sc_trace(mVcdFile, select_ln446_fu_367_p3, "select_ln446_fu_367_p3");
    sc_trace(mVcdFile, tmp_2_fu_387_p3, "tmp_2_fu_387_p3");
    sc_trace(mVcdFile, zext_ln442_fu_383_p1, "zext_ln442_fu_383_p1");
    sc_trace(mVcdFile, zext_ln446_fu_395_p1, "zext_ln446_fu_395_p1");
    sc_trace(mVcdFile, add_ln446_fu_399_p2, "add_ln446_fu_399_p2");
    sc_trace(mVcdFile, icmp_ln480_fu_416_p2, "icmp_ln480_fu_416_p2");
    sc_trace(mVcdFile, icmp_ln480_1_fu_422_p2, "icmp_ln480_1_fu_422_p2");
    sc_trace(mVcdFile, icmp_ln452_fu_452_p2, "icmp_ln452_fu_452_p2");
    sc_trace(mVcdFile, icmp_ln480_8_fu_466_p2, "icmp_ln480_8_fu_466_p2");
    sc_trace(mVcdFile, and_ln480_fu_428_p2, "and_ln480_fu_428_p2");
    sc_trace(mVcdFile, xor_ln480_fu_480_p2, "xor_ln480_fu_480_p2");
    sc_trace(mVcdFile, icmp_ln456_fu_492_p2, "icmp_ln456_fu_492_p2");
    sc_trace(mVcdFile, icmp_ln454_fu_504_p2, "icmp_ln454_fu_504_p2");
    sc_trace(mVcdFile, c2_fu_446_p2, "c2_fu_446_p2");
    sc_trace(mVcdFile, select_ln480_fu_458_p3, "select_ln480_fu_458_p3");
    sc_trace(mVcdFile, and_ln480_18_fu_510_p2, "and_ln480_18_fu_510_p2");
    sc_trace(mVcdFile, or_ln480_fu_530_p2, "or_ln480_fu_530_p2");
    sc_trace(mVcdFile, select_ln480_10_fu_472_p3, "select_ln480_10_fu_472_p3");
    sc_trace(mVcdFile, icmp_ln480_9_fu_544_p2, "icmp_ln480_9_fu_544_p2");
    sc_trace(mVcdFile, and_ln480_19_fu_550_p2, "and_ln480_19_fu_550_p2");
    sc_trace(mVcdFile, and_ln480_16_fu_486_p2, "and_ln480_16_fu_486_p2");
    sc_trace(mVcdFile, xor_ln480_4_fu_564_p2, "xor_ln480_4_fu_564_p2");
    sc_trace(mVcdFile, and_ln480_17_fu_498_p2, "and_ln480_17_fu_498_p2");
    sc_trace(mVcdFile, or_ln480_4_fu_570_p2, "or_ln480_4_fu_570_p2");
    sc_trace(mVcdFile, c5_fu_524_p2, "c5_fu_524_p2");
    sc_trace(mVcdFile, select_ln480_11_fu_536_p3, "select_ln480_11_fu_536_p3");
    sc_trace(mVcdFile, and_ln480_20_fu_576_p2, "and_ln480_20_fu_576_p2");
    sc_trace(mVcdFile, or_ln479_fu_596_p2, "or_ln479_fu_596_p2");
    sc_trace(mVcdFile, or_ln479_4_fu_602_p2, "or_ln479_4_fu_602_p2");
    sc_trace(mVcdFile, c6_6_fu_590_p2, "c6_6_fu_590_p2");
    sc_trace(mVcdFile, add_ln454_4_fu_630_p2, "add_ln454_4_fu_630_p2");
    sc_trace(mVcdFile, add_ln452_4_fu_644_p2, "add_ln452_4_fu_644_p2");
    sc_trace(mVcdFile, tmp_3_fu_689_p3, "tmp_3_fu_689_p3");
    sc_trace(mVcdFile, zext_ln479_7_fu_696_p1, "zext_ln479_7_fu_696_p1");
    sc_trace(mVcdFile, zext_ln479_fu_658_p1, "zext_ln479_fu_658_p1");
    sc_trace(mVcdFile, add_ln479_7_fu_700_p2, "add_ln479_7_fu_700_p2");
    sc_trace(mVcdFile, add_ln479_fu_719_p2, "add_ln479_fu_719_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

PE::~PE() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete local_C_U;
}

void PE::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_0;
}

void PE::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln435_fu_331_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read())) {
                ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state5.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter3 = ap_enable_reg_pp1_iter2.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp1_iter3 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c2_0_reg_265 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        c2_0_reg_265 = select_ln449_fu_516_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c5_0_reg_287 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        c5_0_reg_287 = select_ln452_fu_582_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c61_0_reg_309 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        c61_0_reg_309 = select_ln479_4_reg_786.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln440_fu_343_p2.read()))) {
        c6_0_reg_232 = select_ln446_4_fu_375_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln435_fu_331_p2.read()))) {
        c6_0_reg_232 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c72_0_reg_320 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        c72_0_reg_320 = c7_4_fu_624_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln440_fu_343_p2.read()))) {
        c7_0_reg_243 = c7_fu_410_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln435_fu_331_p2.read()))) {
        c7_0_reg_243 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        indvar_flatten20_reg_276 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        indvar_flatten20_reg_276 = select_ln452_4_fu_650_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        indvar_flatten46_reg_254 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        indvar_flatten46_reg_254 = add_ln449_fu_440_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indvar_flatten53_reg_210 = add_ln435_reg_735.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten53_reg_210 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        indvar_flatten6_reg_298 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        indvar_flatten6_reg_298 = select_ln454_fu_636_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln440_fu_343_p2.read()))) {
        indvar_flatten_reg_221 = add_ln440_fu_349_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln435_fu_331_p2.read()))) {
        indvar_flatten_reg_221 = ap_const_lv3_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln435_reg_735 = add_ln435_fu_337_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln449_reg_758 = icmp_ln449_fu_434_p2.read();
        icmp_ln449_reg_758_pp1_iter1_reg = icmp_ln449_reg_758.read();
        select_ln480_12_reg_772_pp1_iter1_reg = select_ln480_12_reg_772.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln449_reg_758_pp1_iter2_reg = icmp_ln449_reg_758_pp1_iter1_reg.read();
        local_C_addr_4_reg_827_pp1_iter2_reg = local_C_addr_4_reg_827.read();
        select_ln480_12_reg_772_pp1_iter2_reg = select_ln480_12_reg_772_pp1_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        local_C_addr_4_reg_827 =  (sc_lv<2>) (zext_ln479_8_fu_706_p1.read());
        p_Repl2_10_reg_822 = fifo_B_in_V_V_dout.read().range(63, 32);
        p_Repl2_11_reg_807 = p_Repl2_11_fu_661_p1.read();
        p_Repl2_12_reg_812 = fifo_A_in_V_V_dout.read().range(63, 32);
        p_Repl2_s_reg_817 = p_Repl2_s_fu_675_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_reg_758_pp1_iter1_reg.read()))) {
        mul_ln479_1_reg_838 = mul_ln479_1_fu_715_p2.read();
        mul_ln479_reg_833 = mul_ln479_fu_711_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        select_ln479_4_reg_786 = select_ln479_4_fu_616_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_fu_434_p2.read()))) {
        select_ln479_reg_781 = select_ln479_fu_608_p3.read();
        select_ln480_12_reg_772 = select_ln480_12_fu_556_p3.read();
    }
}

void PE::thread_add_ln435_fu_337_p2() {
    add_ln435_fu_337_p2 = (!indvar_flatten53_reg_210.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(indvar_flatten53_reg_210.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void PE::thread_add_ln440_fu_349_p2() {
    add_ln440_fu_349_p2 = (!indvar_flatten_reg_221.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(indvar_flatten_reg_221.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void PE::thread_add_ln446_fu_399_p2() {
    add_ln446_fu_399_p2 = (!zext_ln442_fu_383_p1.read().is_01() || !zext_ln446_fu_395_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln442_fu_383_p1.read()) + sc_biguint<4>(zext_ln446_fu_395_p1.read()));
}

void PE::thread_add_ln449_fu_440_p2() {
    add_ln449_fu_440_p2 = (!indvar_flatten46_reg_254.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten46_reg_254.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void PE::thread_add_ln452_4_fu_644_p2() {
    add_ln452_4_fu_644_p2 = (!indvar_flatten20_reg_276.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten20_reg_276.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void PE::thread_add_ln454_4_fu_630_p2() {
    add_ln454_4_fu_630_p2 = (!indvar_flatten6_reg_298.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten6_reg_298.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void PE::thread_add_ln479_7_fu_700_p2() {
    add_ln479_7_fu_700_p2 = (!zext_ln479_7_fu_696_p1.read().is_01() || !zext_ln479_fu_658_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln479_7_fu_696_p1.read()) + sc_biguint<4>(zext_ln479_fu_658_p1.read()));
}

void PE::thread_add_ln479_fu_719_p2() {
    add_ln479_fu_719_p2 = (!mul_ln479_1_reg_838.read().is_01() || !mul_ln479_reg_833.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln479_1_reg_838.read()) + sc_biguint<32>(mul_ln479_reg_833.read()));
}

void PE::thread_and_ln480_16_fu_486_p2() {
    and_ln480_16_fu_486_p2 = (and_ln480_fu_428_p2.read() & xor_ln480_fu_480_p2.read());
}

void PE::thread_and_ln480_17_fu_498_p2() {
    and_ln480_17_fu_498_p2 = (icmp_ln456_fu_492_p2.read() & xor_ln480_fu_480_p2.read());
}

void PE::thread_and_ln480_18_fu_510_p2() {
    and_ln480_18_fu_510_p2 = (icmp_ln454_fu_504_p2.read() & xor_ln480_fu_480_p2.read());
}

void PE::thread_and_ln480_19_fu_550_p2() {
    and_ln480_19_fu_550_p2 = (select_ln480_10_fu_472_p3.read() & icmp_ln480_9_fu_544_p2.read());
}

void PE::thread_and_ln480_20_fu_576_p2() {
    and_ln480_20_fu_576_p2 = (and_ln480_17_fu_498_p2.read() & or_ln480_4_fu_570_p2.read());
}

void PE::thread_and_ln480_fu_428_p2() {
    and_ln480_fu_428_p2 = (icmp_ln480_fu_416_p2.read() & icmp_ln480_1_fu_422_p2.read());
}

void PE::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void PE::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void PE::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void PE::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void PE::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void PE::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[5];
}

void PE::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  ((esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_in_V_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_in_V_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_out_V_V_full_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_out_V_V_full_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
  esl_seteq<1,1,1>(select_ln480_12_reg_772_pp1_iter2_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_full_n.read())));
}

void PE::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  ((esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_in_V_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_in_V_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_out_V_V_full_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_out_V_V_full_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
  esl_seteq<1,1,1>(select_ln480_12_reg_772_pp1_iter2_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_full_n.read())));
}

void PE::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  ((esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_in_V_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_in_V_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_out_V_V_full_n.read())) || 
   (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_out_V_V_full_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
  esl_seteq<1,1,1>(select_ln480_12_reg_772_pp1_iter2_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_full_n.read())));
}

void PE::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void PE::thread_ap_block_state5_pp1_stage0_iter0() {
    ap_block_state5_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE::thread_ap_block_state6_pp1_stage0_iter1() {
    ap_block_state6_pp1_stage0_iter1 = ((esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_B_out_V_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fifo_A_out_V_V_full_n.read())));
}

void PE::thread_ap_block_state7_pp1_stage0_iter2() {
    ap_block_state7_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE::thread_ap_block_state8_pp1_stage0_iter3() {
    ap_block_state8_pp1_stage0_iter3 = (esl_seteq<1,1,1>(select_ln480_12_reg_772_pp1_iter2_reg.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, fifo_C_drain_out_V_full_n.read()));
}

void PE::thread_ap_condition_pp1_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln449_fu_434_p2.read())) {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_0;
    }
}

void PE::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln435_fu_331_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void PE::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void PE::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void PE::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter3.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void PE::thread_ap_phi_mux_c61_0_phi_fu_313_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0))) {
        ap_phi_mux_c61_0_phi_fu_313_p4 = select_ln479_4_reg_786.read();
    } else {
        ap_phi_mux_c61_0_phi_fu_313_p4 = c61_0_reg_309.read();
    }
}

void PE::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void PE::thread_c2_fu_446_p2() {
    c2_fu_446_p2 = (!ap_const_lv2_1.is_01() || !c2_0_reg_265.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(c2_0_reg_265.read()));
}

void PE::thread_c5_fu_524_p2() {
    c5_fu_524_p2 = (!ap_const_lv2_1.is_01() || !select_ln480_fu_458_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(select_ln480_fu_458_p3.read()));
}

void PE::thread_c6_6_fu_590_p2() {
    c6_6_fu_590_p2 = (!ap_const_lv2_1.is_01() || !select_ln480_11_fu_536_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(select_ln480_11_fu_536_p3.read()));
}

void PE::thread_c6_fu_355_p2() {
    c6_fu_355_p2 = (!c6_0_reg_232.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c6_0_reg_232.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void PE::thread_c7_4_fu_624_p2() {
    c7_4_fu_624_p2 = (!select_ln479_fu_608_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln479_fu_608_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void PE::thread_c7_fu_410_p2() {
    c7_fu_410_p2 = (!select_ln446_fu_367_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln446_fu_367_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void PE::thread_fifo_A_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0))) {
        fifo_A_in_V_V_blk_n = fifo_A_in_V_V_empty_n.read();
    } else {
        fifo_A_in_V_V_blk_n = ap_const_logic_1;
    }
}

void PE::thread_fifo_A_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_A_in_V_V_read = ap_const_logic_1;
    } else {
        fifo_A_in_V_V_read = ap_const_logic_0;
    }
}

void PE::thread_fifo_A_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0))) {
        fifo_A_out_V_V_blk_n = fifo_A_out_V_V_full_n.read();
    } else {
        fifo_A_out_V_V_blk_n = ap_const_logic_1;
    }
}

void PE::thread_fifo_A_out_V_V_din() {
    fifo_A_out_V_V_din = fifo_A_in_V_V_dout.read();
}

void PE::thread_fifo_A_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_A_out_V_V_write = ap_const_logic_1;
    } else {
        fifo_A_out_V_V_write = ap_const_logic_0;
    }
}

void PE::thread_fifo_B_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0))) {
        fifo_B_in_V_V_blk_n = fifo_B_in_V_V_empty_n.read();
    } else {
        fifo_B_in_V_V_blk_n = ap_const_logic_1;
    }
}

void PE::thread_fifo_B_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_B_in_V_V_read = ap_const_logic_1;
    } else {
        fifo_B_in_V_V_read = ap_const_logic_0;
    }
}

void PE::thread_fifo_B_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0))) {
        fifo_B_out_V_V_blk_n = fifo_B_out_V_V_full_n.read();
    } else {
        fifo_B_out_V_V_blk_n = ap_const_logic_1;
    }
}

void PE::thread_fifo_B_out_V_V_din() {
    fifo_B_out_V_V_din = fifo_B_in_V_V_dout.read();
}

void PE::thread_fifo_B_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln449_reg_758.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_B_out_V_V_write = ap_const_logic_1;
    } else {
        fifo_B_out_V_V_write = ap_const_logic_0;
    }
}

void PE::thread_fifo_C_drain_out_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(select_ln480_12_reg_772_pp1_iter2_reg.read(), ap_const_lv1_1))) {
        fifo_C_drain_out_V_blk_n = fifo_C_drain_out_V_full_n.read();
    } else {
        fifo_C_drain_out_V_blk_n = ap_const_logic_1;
    }
}

void PE::thread_fifo_C_drain_out_V_din() {
    fifo_C_drain_out_V_din = tmp_5_fu_723_p2.read();
}

void PE::thread_fifo_C_drain_out_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(select_ln480_12_reg_772_pp1_iter2_reg.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        fifo_C_drain_out_V_write = ap_const_logic_1;
    } else {
        fifo_C_drain_out_V_write = ap_const_logic_0;
    }
}

void PE::thread_icmp_ln435_fu_331_p2() {
    icmp_ln435_fu_331_p2 = (!indvar_flatten53_reg_210.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten53_reg_210.read() == ap_const_lv3_4);
}

void PE::thread_icmp_ln440_fu_343_p2() {
    icmp_ln440_fu_343_p2 = (!indvar_flatten_reg_221.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_221.read() == ap_const_lv3_4);
}

void PE::thread_icmp_ln442_fu_361_p2() {
    icmp_ln442_fu_361_p2 = (!c7_0_reg_243.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c7_0_reg_243.read() == ap_const_lv2_2);
}

void PE::thread_icmp_ln449_fu_434_p2() {
    icmp_ln449_fu_434_p2 = (!indvar_flatten46_reg_254.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten46_reg_254.read() == ap_const_lv5_10);
}

void PE::thread_icmp_ln452_fu_452_p2() {
    icmp_ln452_fu_452_p2 = (!indvar_flatten20_reg_276.read().is_01() || !ap_const_lv5_8.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten20_reg_276.read() == ap_const_lv5_8);
}

void PE::thread_icmp_ln454_fu_504_p2() {
    icmp_ln454_fu_504_p2 = (!indvar_flatten6_reg_298.read().is_01() || !ap_const_lv4_4.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten6_reg_298.read() == ap_const_lv4_4);
}

void PE::thread_icmp_ln456_fu_492_p2() {
    icmp_ln456_fu_492_p2 = (!c72_0_reg_320.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c72_0_reg_320.read() == ap_const_lv2_2);
}

void PE::thread_icmp_ln480_1_fu_422_p2() {
    icmp_ln480_1_fu_422_p2 = (!c5_0_reg_287.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(c5_0_reg_287.read() == ap_const_lv2_1);
}

void PE::thread_icmp_ln480_8_fu_466_p2() {
    icmp_ln480_8_fu_466_p2 = (!c2_0_reg_265.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(c2_0_reg_265.read() == ap_const_lv2_0);
}

void PE::thread_icmp_ln480_9_fu_544_p2() {
    icmp_ln480_9_fu_544_p2 = (!select_ln480_fu_458_p3.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(select_ln480_fu_458_p3.read() == ap_const_lv2_0);
}

void PE::thread_icmp_ln480_fu_416_p2() {
    icmp_ln480_fu_416_p2 = (!c2_0_reg_265.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(c2_0_reg_265.read() == ap_const_lv2_1);
}

void PE::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln435_fu_331_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void PE::thread_local_C_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()))) {
        local_C_address0 = local_C_addr_4_reg_827.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        local_C_address0 =  (sc_lv<2>) (zext_ln446_4_fu_405_p1.read());
    } else {
        local_C_address0 = "XX";
    }
}

void PE::thread_local_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read())))) {
        local_C_ce0 = ap_const_logic_1;
    } else {
        local_C_ce0 = ap_const_logic_0;
    }
}

void PE::thread_local_C_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        local_C_ce1 = ap_const_logic_1;
    } else {
        local_C_ce1 = ap_const_logic_0;
    }
}

void PE::thread_local_C_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln440_fu_343_p2.read()))) {
        local_C_we0 = ap_const_logic_1;
    } else {
        local_C_we0 = ap_const_logic_0;
    }
}

void PE::thread_local_C_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln449_reg_758_pp1_iter2_reg.read()))) {
        local_C_we1 = ap_const_logic_1;
    } else {
        local_C_we1 = ap_const_logic_0;
    }
}

void PE::thread_mul_ln479_1_fu_715_p2() {
    mul_ln479_1_fu_715_p2 = (!p_Repl2_12_reg_812.read().is_01() || !p_Repl2_10_reg_822.read().is_01())? sc_lv<32>(): sc_bigint<32>(p_Repl2_12_reg_812.read()) * sc_bigint<32>(p_Repl2_10_reg_822.read());
}

void PE::thread_mul_ln479_fu_711_p2() {
    mul_ln479_fu_711_p2 = (!p_Repl2_11_reg_807.read().is_01() || !p_Repl2_s_reg_817.read().is_01())? sc_lv<32>(): sc_bigint<32>(p_Repl2_11_reg_807.read()) * sc_bigint<32>(p_Repl2_s_reg_817.read());
}

void PE::thread_or_ln479_4_fu_602_p2() {
    or_ln479_4_fu_602_p2 = (or_ln479_fu_596_p2.read() | icmp_ln452_fu_452_p2.read());
}

void PE::thread_or_ln479_fu_596_p2() {
    or_ln479_fu_596_p2 = (and_ln480_20_fu_576_p2.read() | and_ln480_18_fu_510_p2.read());
}

void PE::thread_or_ln480_4_fu_570_p2() {
    or_ln480_4_fu_570_p2 = (icmp_ln452_fu_452_p2.read() | xor_ln480_4_fu_564_p2.read());
}

void PE::thread_or_ln480_fu_530_p2() {
    or_ln480_fu_530_p2 = (and_ln480_18_fu_510_p2.read() | icmp_ln452_fu_452_p2.read());
}

void PE::thread_p_Repl2_11_fu_661_p1() {
    p_Repl2_11_fu_661_p1 = fifo_A_in_V_V_dout.read().range(32-1, 0);
}

void PE::thread_p_Repl2_s_fu_675_p1() {
    p_Repl2_s_fu_675_p1 = fifo_B_in_V_V_dout.read().range(32-1, 0);
}

void PE::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void PE::thread_select_ln446_4_fu_375_p3() {
    select_ln446_4_fu_375_p3 = (!icmp_ln442_fu_361_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln442_fu_361_p2.read()[0].to_bool())? c6_fu_355_p2.read(): c6_0_reg_232.read());
}

void PE::thread_select_ln446_fu_367_p3() {
    select_ln446_fu_367_p3 = (!icmp_ln442_fu_361_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln442_fu_361_p2.read()[0].to_bool())? ap_const_lv2_0: c7_0_reg_243.read());
}

void PE::thread_select_ln449_fu_516_p3() {
    select_ln449_fu_516_p3 = (!icmp_ln452_fu_452_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln452_fu_452_p2.read()[0].to_bool())? c2_fu_446_p2.read(): c2_0_reg_265.read());
}

void PE::thread_select_ln452_4_fu_650_p3() {
    select_ln452_4_fu_650_p3 = (!icmp_ln452_fu_452_p2.read()[0].is_01())? sc_lv<5>(): ((icmp_ln452_fu_452_p2.read()[0].to_bool())? ap_const_lv5_1: add_ln452_4_fu_644_p2.read());
}

void PE::thread_select_ln452_fu_582_p3() {
    select_ln452_fu_582_p3 = (!and_ln480_18_fu_510_p2.read()[0].is_01())? sc_lv<2>(): ((and_ln480_18_fu_510_p2.read()[0].to_bool())? c5_fu_524_p2.read(): select_ln480_fu_458_p3.read());
}

void PE::thread_select_ln454_fu_636_p3() {
    select_ln454_fu_636_p3 = (!or_ln480_fu_530_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln480_fu_530_p2.read()[0].to_bool())? ap_const_lv4_1: add_ln454_4_fu_630_p2.read());
}

void PE::thread_select_ln479_4_fu_616_p3() {
    select_ln479_4_fu_616_p3 = (!and_ln480_20_fu_576_p2.read()[0].is_01())? sc_lv<2>(): ((and_ln480_20_fu_576_p2.read()[0].to_bool())? c6_6_fu_590_p2.read(): select_ln480_11_fu_536_p3.read());
}

void PE::thread_select_ln479_fu_608_p3() {
    select_ln479_fu_608_p3 = (!or_ln479_4_fu_602_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln479_4_fu_602_p2.read()[0].to_bool())? ap_const_lv2_0: c72_0_reg_320.read());
}

void PE::thread_select_ln480_10_fu_472_p3() {
    select_ln480_10_fu_472_p3 = (!icmp_ln452_fu_452_p2.read()[0].is_01())? sc_lv<1>(): ((icmp_ln452_fu_452_p2.read()[0].to_bool())? icmp_ln480_8_fu_466_p2.read(): icmp_ln480_fu_416_p2.read());
}

void PE::thread_select_ln480_11_fu_536_p3() {
    select_ln480_11_fu_536_p3 = (!or_ln480_fu_530_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln480_fu_530_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_c61_0_phi_fu_313_p4.read());
}

void PE::thread_select_ln480_12_fu_556_p3() {
    select_ln480_12_fu_556_p3 = (!and_ln480_18_fu_510_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln480_18_fu_510_p2.read()[0].to_bool())? and_ln480_19_fu_550_p2.read(): and_ln480_16_fu_486_p2.read());
}

void PE::thread_select_ln480_fu_458_p3() {
    select_ln480_fu_458_p3 = (!icmp_ln452_fu_452_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln452_fu_452_p2.read()[0].to_bool())? ap_const_lv2_0: c5_0_reg_287.read());
}

void PE::thread_start_out() {
    start_out = real_start.read();
}

void PE::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void PE::thread_tmp_2_fu_387_p3() {
    tmp_2_fu_387_p3 = esl_concat<2,1>(select_ln446_fu_367_p3.read(), ap_const_lv1_0);
}

void PE::thread_tmp_3_fu_689_p3() {
    tmp_3_fu_689_p3 = esl_concat<2,1>(select_ln479_reg_781.read(), ap_const_lv1_0);
}

void PE::thread_tmp_5_fu_723_p2() {
    tmp_5_fu_723_p2 = (!local_C_q0.read().is_01() || !add_ln479_fu_719_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(local_C_q0.read()) + sc_biguint<32>(add_ln479_fu_719_p2.read()));
}

void PE::thread_xor_ln480_4_fu_564_p2() {
    xor_ln480_4_fu_564_p2 = (icmp_ln454_fu_504_p2.read() ^ ap_const_lv1_1);
}

void PE::thread_xor_ln480_fu_480_p2() {
    xor_ln480_fu_480_p2 = (icmp_ln452_fu_452_p2.read() ^ ap_const_lv1_1);
}

void PE::thread_zext_ln442_fu_383_p1() {
    zext_ln442_fu_383_p1 = esl_zext<4,2>(select_ln446_4_fu_375_p3.read());
}

void PE::thread_zext_ln446_4_fu_405_p1() {
    zext_ln446_4_fu_405_p1 = esl_zext<64,4>(add_ln446_fu_399_p2.read());
}

void PE::thread_zext_ln446_fu_395_p1() {
    zext_ln446_fu_395_p1 = esl_zext<4,3>(tmp_2_fu_387_p3.read());
}

void PE::thread_zext_ln479_7_fu_696_p1() {
    zext_ln479_7_fu_696_p1 = esl_zext<4,3>(tmp_3_fu_689_p3.read());
}

void PE::thread_zext_ln479_8_fu_706_p1() {
    zext_ln479_8_fu_706_p1 = esl_zext<64,4>(add_ln479_7_fu_700_p2.read());
}

void PE::thread_zext_ln479_fu_658_p1() {
    zext_ln479_fu_658_p1 = esl_zext<4,2>(select_ln479_4_reg_786.read());
}

void PE::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln435_fu_331_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln440_fu_343_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 16 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln449_fu_434_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln449_fu_434_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

